### ISSUE TITLE
新增数据库资源时无法输入密码

### ISSUE THREAD

**Issue by BenJaMiniature** [WeBankPartners/we-cmdb#1028]
**描述您遇到的bug**  
新增单条数据库实例时，可以正常输入密码；
新增数据库实例选择2或更多实例点确定后，“输入密码”按钮消失；
复制新增多个数据库实例同样问题，没有“输入密码”按钮。

**如何重现** 

**预期行为** 

**截图**  
![image](https://user-images.githubusercontent.com/52971115/89521580-5547c800-d812-11ea-9e51-30942dbd83fe.png)
![image](https://user-images.githubusercontent.com/52971115/89521609-6395e400-d812-11ea-9c20-5ac3df81b60a.png)
![image](https://user-images.githubusercontent.com/52971115/89521411-0732c480-d812-11ea-9f43-8f1ef63bfbd1.png)

**附加**

**Comment by zgyzgyhero** [comment]
已修复
