### ISSUE TITLE
make build 编译失败提示package io.jsonwebtoken.lang does not exist

### ISSUE THREAD

**Issue by huangmeng4520** [WeBankPartners/we-cmdb#1031]
**描述您遇到的bug**  
[INFO] Reactor Summary:
[INFO] 
[INFO] cmdb-ui ............................................ SUCCESS [02:22 min]
[INFO] cmdb-core .......................................... FAILURE [  4.946 s]
[INFO] cmdb ............................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:28 min
[INFO] Finished at: 2020-08-07T03:26:55+00:00
[INFO] Final Memory: 77M/1207M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project cmdb-core: Compilation failure
[ERROR] /usr/src/mymaven/cmdb-core/src/main/java/com/webank/cmdb/support/security/RoleCiTypeRuleAuthority.java:[16,28] package io.jsonwebtoken.lang does not exist
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :cmdb-core
make: *** [build] Error 1

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by huangmeng4520** [comment]
cmdb-core的pom.xml依赖包需要增加如下依赖


<dependency>
    <groupId>io.jsonwebtoken</groupId>
    <artifactId>jjwt</artifactId>
    <version>0.9.1</version>
</dependency>

**Comment by huangmeng4520** [comment]
cmdb-core的pom.xml依赖包需要增加如下依赖

`
<dependency>
    <groupId>io.jsonwebtoken</groupId>
    <artifactId>jjwt</artifactId>
    <version>0.9.1</version>
</dependency>
`

**Comment by zhanghongxia4725** [comment]
楼主跑起来了吗？我在docker中运行镜像报错，本地尝试开发环境启动也报错

**Comment by royl88** [comment]
您好，基于最新代码build是否还存在疑问？若无进一步讨论，ISSUE将在10天后关闭
