### ISSUE TITLE
table新增组件select获取数据返回字段过滤

### ISSUE THREAD

**Issue by pobu168** [WeBankPartners/we-cmdb#1041]
**描述您的需求**  
限制返回字段后将提升接口速度，提升界面响应速度

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by junchensz** [comment]
Ci数据接口请求可以加上resultColumns来获取期望的数据字段，
{
    "resultColumns":["guid","key_name"],
    "filters": [],
    "paging": false
}

**Comment by pobu168** [comment]
id, des
