### ISSUE TITLE
docker部署报错如下

### ISSUE THREAD

**Issue by zhanghongxia4725** [WeBankPartners/we-cmdb#1044]
[root@test2 wecmdb]# docker-compose -f 2-cmdb-app.yml up -d
/usr/lib64/python2.7/site-packages/cryptography/__init__.py:39: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  CryptographyDeprecationWarning,
WARNING: Found orphan containers (wecmdb_wecmdb-mysql_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Pulling wecmdb-app (ccr.ccs.tencentyun.com/webankpartners/wecmdb-app:1.0)...
ERROR: Get https://ccr.ccs.tencentyun.com/v2/webankpartners/wecmdb-app/manifests/1.0: unauthorized: authentication required
[root@test2 wecmdb]# 

![捕获](https://user-images.githubusercontent.com/67135700/90703805-60463200-e2c1-11ea-9af2-6c4132014fe4.PNG)

**Comment by royl88** [comment]
基于docker进行本地搭建使用，搭建教程可参照[CMDB独立部署](https://github.com/WeBankPartners/we-cmdb/releases/download/v1.5.1/CMDB.zip)
链接包含：步骤说明文件，yaml，离线镜像，最佳实践sql

**Comment by royl88** [comment]
您好，根据我们提供的部署指引是否部署成功？
若无进一步讨论，ISSUE将在10天后关闭
