### ISSUE TITLE
we-cmdb编译时（v1.5.1）报错

### ISSUE THREAD

**Issue by nzxxs4** [WeBankPartners/we-cmdb#1046]
​您好，我在按照https://gitee.com/WeBank/we-cmdb/blob/master/README.md中的教程搭建we-cmdb，在make build 的时候会报下面的错误 请问是什么问题，望赐教抱拳感谢！！
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[root@bogon ~]# cd /data/we-cmdb
[root@bogon we-cmdb]# make build 
mkdir -p repository
docker run --rm --name wecmdb-build -v /data/repository:/usr/src/mymaven/repository   -v /data/we-cmdb/build/maven_settings.xml:/usr/share/maven/ref/settings-docker.xml  -v /data/we-cmdb:/usr/src/mymaven -w /usr/src/mymaven maven:3.3-jdk-8 mvn -U clean install -Dmaven.test.skip=true -s /usr/share/maven/ref/settings-docker.xml dependency:resolve
[INFO] Scanning for projects...
Downloading: http://maven.aliyun.com/nexus/content/groups/public/org/springframework/boot/spring-boot-starter-parent/2.1.3.RELEASE/spring-boot-starter-parent-2.1.3.RELEASE.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'version' contains an expression but should be a constant. @ line 21, column 11
[FATAL] Non-resolvable parent POM for com.webank.cmdb:cmdb:${cmdb.version}: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:2.1.3.RELEASE from/to nexus-aliyun (http://maven.aliyun.com/nexus/content/groups/public/): maven.aliyun.com: Temporary failure in name resolution and 'parent.relativePath' points at no local POM @ line 6, column 10
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.webank.cmdb:cmdb:${cmdb.version} (/usr/src/mymaven/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.webank.cmdb:cmdb:${cmdb.version}: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:2.1.3.RELEASE from/to nexus-aliyun (http://maven.aliyun.com/nexus/content/groups/public/): maven.aliyun.com: Temporary failure in name resolution and 'parent.relativePath' points at no local POM @ line 6, column 10: Unknown host maven.aliyun.com: Temporary failure in name resolution -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
make: *** [build] 错误 1
[root@bogon we-cmdb]#

**Comment by kanetz** [comment]
您好，您在构建过程中的报错原因在日志中显示的是对阿里云Maven镜像站点域名的临时性解析失败：
```
Unknown host maven.aliyun.com: Temporary failure in name resolution
```

看上去，您应该在自己的maven settings文件里设置了使用阿里云Maven仓库镜像，请直接访问阿里云的Maven镜像站点 http://maven.aliyun.com/ 来确保您的网络连通，或者更换其它的镜像站点使用。

**Comment by royl88** [comment]
若无进一步讨论，将关闭issue
