### ISSUE TITLE
试用链接貌似坏掉了

### ISSUE THREAD

**Issue by Bazinga-Wang** [WeBankPartners/we-cmdb#1055]
**描述您遇到的bug**  
点击https://sandbox.webank.com/wecmdb/ 提示无法访问网站

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by royl88** [comment]
由于资源关系，前期确实对sandbox资源进行了关闭，我们推荐基于docker进行本地搭建使用，搭建教程可参照[CMDB独立部署](https://github.com/WeBankPartners/we-cmdb/releases/download/v1.5.1/CMDB.zip)
