### ISSUE TITLE
cmdb编译错误

### ISSUE THREAD

**Issue by zhangjianweibj** [WeBankPartners/we-cmdb#1059]
![image](https://user-images.githubusercontent.com/18585129/91296031-8d697780-e7ce-11ea-8a34-98beed6207fe.png)

按照说明，make build错误。
https://github.com/WeBankPartners/we-cmdb/blob/master/cmdb-wiki/docs/install/wecmdb_compile_guide.md

**Comment by royl88** [comment]
从截图这里的报错信息来看，是前端编译打包时npm安装外部依赖失败了，可能时npm长时间下载缓慢导致，您可以尝试手动执行:
cd {仓库目录}/cmdb-ui
npm --registry https://registry.npm.taobao.org install
确认npm安装依赖成功，可以重新执行make build进行编译

**Comment by royl88** [comment]
您好，按照最后给出的建议重新build是否成功？
若无进一步讨论，ISSUE将在10天后关闭
