### ISSUE TITLE
综合查询无法删除节点

### ISSUE THREAD

**Issue by junchensz** [WeBankPartners/we-cmdb#1089]
**描述您遇到的bug**  
一个现有的综合查询
![image](https://user-images.githubusercontent.com/8709231/92214885-a9ec6a80-eec6-11ea-8a7b-dd31c6c210af.png)

当打开"应用实例"节点，“部署包”节点并没有被勾选, 无法删除2-1部署包，
![image](https://user-images.githubusercontent.com/8709231/92215223-08b1e400-eec7-11ea-8a88-743c9d2f5c34.png)

**如何重现** 
当打开"应用实例"节点，“部署包”节点应该被勾选，可以去掉勾选来删除相应节点

**预期行为** 

**截图**  

**附加**

**Comment by zgyzgyhero** [comment]
新版本已修复
