### ISSUE TITLE
保存综合查询成功后，对话框并不消失

### ISSUE THREAD

**Issue by junchensz** [WeBankPartners/we-cmdb#1090]
**描述您遇到的bug**  
添加综合查询时，点击对话框的保存按钮，提示保存成功后，对话框并不消失。

![image](https://user-images.githubusercontent.com/8709231/92216408-d99c7200-eec8-11ea-97a5-fa9f84b99789.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by pobu168** [comment]
Fixed
