### ISSUE TITLE
docker镜像的快速演示版，可否增加演示数据

### ISSUE THREAD

**Issue by pugwoo** [WeBankPartners/we-cmdb#1093]
**描述您的需求**  

docker镜像的演示版，里面的init.sql只有基本的几个数据，项目启动之后，体验不出主要功能。另外，页面增加数据好像也有点走不通，可否外加一个视频示例下呢？

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by royl88** [comment]
已增加模型及数据，详情见: [Release v1.5.2](https://github.com/WeBankPartners/we-cmdb/releases/tag/v1.5.2)，可直接导入sql到CMDB系统中。
另外使用过程中可参考指引文档[CMDB操作指引](http://webankpartners.gitee.io/wecube-docs/manual-cmdb-model/)，欢迎随时提问
