### ISSUE TITLE
前端start的时候 ERROR  TypeError: Cannot read property 'upgrade' of undefined

### ISSUE THREAD

**Issue by gpp1994** [WeBankPartners/we-cmdb#1100]
**描述您遇到的bug**  
前端启动的时候报错
 ERROR  TypeError: Cannot read property 'upgrade' of undefined

**如何重现** 

**预期行为** 

**截图**  
![image](https://user-images.githubusercontent.com/35265270/92445068-62c3e980-f1e6-11ea-9410-120f046a4a74.png)

**附加**

**Comment by gpp1994** [comment]
![image](https://user-images.githubusercontent.com/35265270/92477200-c532df00-f212-11ea-9fe7-3aea7f89f0b8.png)
![image](https://user-images.githubusercontent.com/35265270/92477226-d4b22800-f212-11ea-9a70-ddc547bf1c2f.png)
修改vue.config.js连不上后台。。。。求指导

**Comment by gpp1994** [comment]
jiejue l

**Comment by r278318485** [comment]
我想问下后面这个Could not proxy request /wecmdb/ui/v2/my-menus from localhost:3000 to localhost:9080.是怎么解决的

**Comment by tongs-hub** [comment]
ERROR TypeError: Cannot read property 'upgrade' of undefined 请问怎么解决？
