### ISSUE TITLE
CI数据导出后显示错位

### ISSUE THREAD

**Issue by haixinhuang** [WeBankPartners/we-cmdb#1105]
**描述您遇到的bug**  
导出数据的文件显示错位

**如何重现** 
导出一个CI，该CI的某一列中含有逗号

**预期行为** 
能正常显示

**截图**  
![image](https://user-images.githubusercontent.com/22583258/92678312-4ba50900-f358-11ea-9a70-f3d324c71551.png)

**附加**

**Comment by royl88** [comment]
v1.5.3已修复
