### ISSUE TITLE
编译部署时报错

### ISSUE THREAD

**Issue by sunleoyao** [WeBankPartners/we-cmdb#1128]
**描述您遇到的bug**  
编译安装make build时，遇到以下报错

**如何重现** 
修改maven_setting
添加以下源
    <mirror>
      <id>alimaven</id>
      <name>aliyun maven</name>
  　　<url>http://maven.aliyun.com/nexus/content/groups/public/</url>
      <mirrorOf>central</mirrorOf>
    </mirror>

**预期行为** 

**截图**  
![image](https://user-images.githubusercontent.com/16498590/95562712-1a028900-0a4f-11eb-95e3-f0199eef7e4d.png)

**附加**

**Comment by royl88** [comment]
platform-auth-client依赖 计划在v0.5.0版本中移除，此版本最新代码在dev分支中，切换到dev分支编译即可，按计划将在2020.10.11会进行合并到master。

**Comment by royl88** [comment]
问题已解决，可以重新pull master进行编译。

**Comment by sunleoyao** [comment]
十分感谢！
