### ISSUE TITLE
前端启动

### ISSUE THREAD

**Issue by r278318485** [WeBankPartners/we-cmdb#1129]
**描述您遇到的bug**  
后端已经ok
前端首页没有架构图显示

**如何重现** 
前端vue.config.js文件设置baseUrl = 'http://localhost:9080'
然后npm start

**预期行为** 
WeCMDB 开发环境配置文档里面的前端登录  有架构图显示

**截图**  
![20201009174557](https://user-images.githubusercontent.com/55784749/95568833-4e7a4300-0a57-11eb-8721-54525ad3108e.png)
![image](https://user-images.githubusercontent.com/55784749/95569632-68685580-0a58-11eb-95ea-9b184799de1c.png)

**附加**
这里设置baseUrl = 'http://localhost:9080'，ui启动http://localhost:3000/wecmdb/这个直接就跳转http://localhost:9080/wecmdb/了，而跳转的9080这个路径我试了下不启动ui也能访问，我前端经验比较少，在这里比较疑惑，是不是压根就没访问到真正的前端页面所以首页结构图才没显示？还是说是第二幅图里console报错导致的？

**Comment by royl88** [comment]
了解一下，您是希望自己部署一个CMDB环境？还是希望本地进行开发调试？

**Comment by r278318485** [comment]
本地进行开发调试

**Comment by xuxuzhesi** [comment]
跳转到9080端口后再手动改回3000看下什么现象
