### ISSUE TITLE
配置项类型关联关系 (CITR - Configuraiton Item Type Relationship) 如何设置？

### ISSUE THREAD

**Issue by androip** [WeBankPartners/we-cmdb#1134]
**描述您的需求**  

本人尝试添加CI如下：
![image](https://user-images.githubusercontent.com/8563089/95660471-bcf3f980-0b5a-11eb-9229-19c8b61559e6.png)
添加4个CI后：
![image](https://user-images.githubusercontent.com/8563089/95660436-7bfbe500-0b5a-11eb-9f42-795ed2deaf5a.png)
整个过程没有发现如何配置CI关联关系的相关环节，
数据库CI相关表如下：
![image](https://user-images.githubusercontent.com/8563089/95660576-72bf4800-0b5b-11eb-85f0-4b9ff48e3fe3.png)

并没有发现存储CI关系的表。
请问是否有意隐藏了该功能？
**预期行为**  

能够看到配置CI 关联关系的界面
**描述您考虑过的替代方案**  

**附加**

**Comment by royl88** [comment]
没有隐藏，详见：CMDB模型管理，数据类型选择ref或multiref即配置关联类型。
![image](https://user-images.githubusercontent.com/23582722/95697317-f0c14300-0c70-11eb-9fce-cef1a7e53e70.png)

**Comment by androip** [comment]
多谢
