### ISSUE TITLE
数据库初始化数据不全

### ISSUE THREAD

**Issue by androip** [WeBankPartners/we-cmdb#1137]
**描述您遇到的bug**  
“视图管理”的子菜单下的所有查询都报错了，原因是找不到ciTypeId对应的数据。
对应接口：http://localhost:9080/wecmdb/ui/v2/ci-types
源码中该接口硬式传参，ID作为常量向表adm_ci_type查询，
但数据库初始化数据脚本并无上述id对应的数据。

**如何重现** 

**预期行为** 
能够查到常量ID对应的数据。

**截图**  

![image](https://user-images.githubusercontent.com/8563089/95720012-40206700-0ca3-11eb-8343-24d4c5d978c1.png)

![image](https://user-images.githubusercontent.com/8563089/95720732-33504300-0ca4-11eb-81dc-1c1edec1f039.png)

**附加**
其他页面也有类似问题，请提供较完整的数据库初始化脚本

**Comment by royl88** [comment]
可以从：https://github.com/WeBankPartners/we-cmdb/releases/tag/v1.5.3下载最新模型，导入wecmdb_model_init.zip数据
