### ISSUE TITLE
maven 打包时出错

### ISSUE THREAD

**Issue by shushu1234** [WeBankPartners/we-cmdb#1138]
**描述您遇到的bug**  
[INFO] 14 warnings
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /F:/WeCube-CMDB/we-cmdb/cmdb-core/src/main/java/com/webank/cmdb/config/SpringWebConfig.java:[205,50] ▒▒▒▒JwtSsoBasedAuthenticationFilter(org.springframework.security.authentication.AuthenticationManager), ▒Ҳ▒▒▒▒▒▒ʵĹ▒▒▒▒▒
    ▒▒▒▒▒▒ com.webank.wecube.platform.auth.client.filter.JwtSsoBasedAuthenticationFilter.JwtSsoBasedAuthenticationFilter(org.springframework.security.authentication.AuthenticationManager,com.webank.wecube.platform.auth.client.filter.JwtClientConfig)▒▒▒▒▒▒
      (ʵ▒ʲ▒▒▒▒б▒▒▒▒ʽ▒▒▒▒▒б▒▒Ȳ▒ͬ)
    ▒▒▒▒▒▒ com.webank.wecube.platform.auth.client.filter.JwtSsoBasedAuthenticationFilter.JwtSsoBasedAuthenticationFilter(org.springframework.security.authentication.AuthenticationManager,org.springframework.security.web.AuthenticationEntryPoint,com.webank.wecube.platform.auth.client.filter.JwtClientConfig)▒▒▒▒▒▒
      (ʵ▒ʲ▒▒▒▒б▒▒▒▒ʽ▒▒▒▒▒б▒▒Ȳ▒ͬ)
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for cmdb 1.5.0:
[INFO]
[INFO] cmdb ............................................... SUCCESS [  0.309 s]
[INFO] cmdb-ui ............................................ SUCCESS [01:54 min]
[INFO] cmdb-core .......................................... FAILURE [ 10.667 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:05 min
[INFO] Finished at: 2020-10-12T16:53:16+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project cmdb-core: Compilation failure
[ERROR] /F:/WeCube-CMDB/we-cmdb/cmdb-core/src/main/java/com/webank/cmdb/config/SpringWebConfig.java:[205,50] ▒▒▒▒JwtSsoBasedAuthenticationFilter(org.springframework.security.authentication.AuthenticationManager), ▒Ҳ▒▒▒▒▒▒ʵĹ▒▒▒▒▒
[ERROR]     ▒▒▒▒▒▒ com.webank.wecube.platform.auth.client.filter.JwtSsoBasedAuthenticationFilter.JwtSsoBasedAuthenticationFilter(org.springframework.security.authentication.AuthenticationManager,com.webank.wecube.platform.auth.client.filter.JwtClientConfig)▒▒▒▒▒▒
[ERROR]       (ʵ▒ʲ▒▒▒▒б▒▒▒▒ʽ▒▒▒▒▒б▒▒Ȳ▒ͬ)
[ERROR]     ▒▒▒▒▒▒ com.webank.wecube.platform.auth.client.filter.JwtSsoBasedAuthenticationFilter.JwtSsoBasedAuthenticationFilter(org.springframework.security.authentication.AuthenticationManager,org.springframework.security.web.AuthenticationEntryPoint,com.webank.wecube.platform.auth.client.filter.JwtClientConfig)▒▒▒▒▒▒
[ERROR]       (ʵ▒ʲ▒▒▒▒б▒▒▒▒ʽ▒▒▒▒▒б▒▒Ȳ▒ͬ)
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :cmdb-core

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by royl88** [comment]
原因是CMDB v1.5.3版本之前会依赖于wecube的auth-client包，因此需要先编译wecube项目然后才能编译cmdb项目
master当前(v1.5.3)已经将此项依赖移除，可以尝试重新pull master代码重新编译

**Comment by shushu1234** [comment]
感谢你的解答^-^
