### ISSUE TITLE
主机资源CRUD API

### ISSUE THREAD

**Issue by duanshuaimin** [WeBankPartners/we-cmdb#1143]
**描述您的需求**  
我有一个DCIM系统，需要将主机资源导入cmdb，看文档有提供这方面的API，但没找到实现，是否目前还没有提供？

**预期行为**  
外部系统主机资源与cmdb同步

**描述您考虑过的替代方案**  
还没有

**附加**

**Comment by chaneyliu** [comment]
独立运行版的WeCMDB，目前没有单独提供接口。你可以复用前端新增数据的接口，/wecmdb/ui/v2/ci-types/{citypeid}/ci-data/batch-create，来实现数据批量导入。报文内容类似如下[{"guid":"","p_guid":"","r_guid":"","updated_by":"","updated_date":"","created_by":"","created_date":"","state":"","fixed_date":"","code":"SSS","name":"SSS","application_domain":"0005_0000000002","app_system_design_id":"2345","data_center_design":"0012_0000000002"},{"guid":"","p_guid":"","r_guid":"","updated_by":"","updated_date":"","created_by":"","created_date":"","state":"","fixed_date":"","code":"SSS","name":"SDSS","application_domain":"0005_0000000002","app_system_design_id":"2346","data_center_design":"0012_0000000002"}]

**Comment by duanshuaimin** [comment]
感谢及时回复，我也是比较了蓝鲸之后选的这个项目，感谢wecmdb，以后是否有计划提供，platform 有提供吗
🙏

**Comment by chaneyliu** [comment]
作为插件集成到platform，也是提供了类似的插件方法ci-data-create，跟页面增加数据类似。 
有计划基于terrafrom实现公有云资源数据的导入cmdb的功能，预计会在12月底或明年1月底版本正式发布。非公有云的目前暂时没有计划。
