### ISSUE TITLE
we-cmdb:v1.5.3容器启动报错：/scripts/start.sh: line 15: can't create /data/wecmdb/log/wecmdb-core.log: nonexistent directory

### ISSUE THREAD

**Issue by xuli2020-web** [WeBankPartners/we-cmdb#1151]
**描述您遇到的bug**  
we-cmdb启动报错：/scripts/start.sh: line 15: can't create /data/wecmdb/log/wecmdb-core.log: nonexistent directory

**如何重现** 
git clone https://github.com/WeBankPartners/we-cmdb.git  ---生产的目录是/data/we-cmdb
但是又要在/data/wecmdb里生成log

**预期行为** 

**截图**  

**附加**

**Comment by xuli2020-web** [comment]
[root@devops-cmdb build]# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                        PORTS                    NAMES
e1558204f08a        we-cmdb:v1.5.3      "/bin/sh -c /scripts…"   10 minutes ago      Restarting (1) 1 second ago                            build_wecmdb-app_1
2734edbccbeb        cmdb-db:dev         "docker-entrypoint.s…"   10 minutes ago      Up 10 minutes                 0.0.0.0:3306->3306/tcp   build_wecmdb-mysql_1
[root@devops-cmdb build]# docker logs e1558204f08a
/scripts/start.sh: line 15: can't create /data/wecmdb/log/wecmdb-core.log: nonexistent directory
/scripts/start.sh: line 15: can't create /data/wecmdb/log/wecmdb-core.log: nonexistent directory
/scripts/start.sh: line 15: can't create /data/wecmdb/log/wecmdb-core.log: nonexistent directory
/scripts/start.sh: line 15: can't create /data/wecmdb/log/wecmdb-core.log: nonexistent directory
/scripts/start.sh: line 15: can't create /data/wecmdb/log/wecmdb-core.log: nonexistent directory
/scripts/start.sh: line 15: can't create /data/wecmdb/log/wecmdb-core.log: nonexistent directory
/scripts/start.sh: line 15: can't create /data/wecmdb/log/wecmdb-core.log: nonexistent directory
/scripts/start.sh: line 15: can't create /data/wecmdb/log/wecmdb-core.log: nonexistent directory
/scripts/start.sh: line 15: can't create /data/wecmdb/log/wecmdb-core.log: nonexistent directory
/scripts/start.sh: line 15: can't create /data/wecmdb/log/wecmdb-core.log: nonexistent directory
/scripts/start.sh: line 15: can't create /data/wecmdb/log/wecmdb-core.log: nonexistent directory
/scripts/start.sh: line 15: can't create /data/wecmdb/log/wecmdb-core.log: nonexistent directory
/scripts/start.sh: line 15: can't create /data/wecmdb/log/wecmdb-core.log: nonexistent directory
/scripts/start.sh: line 15: can't create /data/wecmdb/log/wecmdb-core.log: nonexistent directory
/scripts/start.sh: line 15: can't create /data/wecmdb/log/wecmdb-core.log: nonexistent directory
/scripts/start.sh: line 15: can't create /data/wecmdb/log/wecmdb-core.log: nonexistent directory

**Comment by xuli2020-web** [comment]
生成的目录是/data/we-cmdb
git clone https://github.com/WeBankPartners/we-cmdb.git 
但是又要在/data/wecmdb里生成log

**Comment by royl88** [comment]
没有重现这个问题，目前docker数据路径映射都是/data/wecmdb，请问哪个文档和什么情况下生成/data/we-cmdb目录使用呢

**Comment by afghanistanyn** [comment]
1. 下载release包，导入镜

**Comment by royl88** [comment]
好的，我们修改一下这个配置。
这是因为CMDB存在独立版和插件版打包的差别

**Comment by royl88** [comment]
最新Release已修复
