### ISSUE TITLE
按照文档步骤配置环境后，前后端服务可正常启动，但创建CI后提交就报错

### ISSUE THREAD

**Issue by jsonLiChina** [WeBankPartners/we-cmdb#1168]
**描述您遇到的bug**  
按照文档步骤配置环境后，前后端服务可正常启动，但创建CI后提交就报错

**如何重现** 
创建图层-创建层级-创建CI-暂存-提交-报错

**预期行为** 
Can not create ciType [name = 测试随便] with reference id of property name [state] is null.

**截图**  

**附加**

**Comment by chaneyliu** [comment]
你好，因为有状态机限制，所有CI创建，必须选选择“状态”类型，然后在提交CI创建。
![image](https://user-images.githubusercontent.com/54091452/99923763-2f6b1280-2d72-11eb-9280-dc88f3e2a46c.png)
