### ISSUE TITLE
启动的时候就展示这个，然后浏览器访问地址 没法访问

### ISSUE THREAD

**Issue by jadeball** [WeBankPartners/we-cmdb#1175]
**描述您遇到的bug**  
![image](https://user-images.githubusercontent.com/610187/100957442-6650dd80-3555-11eb-90df-7846787147c2.png)

D:\project\test\we-cmdb>java -jar -Dspring.profiles.active=ch-local D:\project\test\we-cmdb\cmdb-core\target\cmdb-core-1.5.0.jar

 ____      ____        ______  ____    ____  ______   ______
|_  _|    |_  _|     .' ___  ||_   \  /   _||_   _ `.|_   _ \
  \ \  /\  / /.---. / .'   \_|  |   \/   |    | | `. \ | |_) |
   \ \/  \/ // /__\\| |         | |\  /| |    | |  | | |  __'.
    \  /\  / | \__.,\ `.___.'\ _| |_\/_| |_  _| |_.' /_| |__) |
     \/  \/   '.__.' `.____ .'|_____||_____||______.'|_______/

D:\project\test\we-cmdb>

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by royl88** [comment]
您好
1. 请确认程序配置参数正确，具体需要修改的参数见源码build/start.sh文件
```bash
java -jar /application/cmdb-core.jar ${JAVA_OPT} --server.address=0.0.0.0 --server.port=${CMDB_SERVER_PORT} --server.servlet.context-path=/wecmdb  \
--spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver \
--spring.datasource.url=jdbc:mysql://${MYSQL_SERVER_ADDR}:${MYSQL_SERVER_PORT}/${MYSQL_SERVER_DATABASE_NAME}?serverTimezone=Asia\/Shanghai\&characterEncoding=utf8  \
--spring.datasource.username=${MYSQL_USER_NAME} \
--spring.datasource.password=${MYSQL_USER_PASSWORD}  \
--cmdb.datasource.schema=${MYSQL_SERVER_DATABASE_NAME} \
--cmdb.security.enabled=false \
--cmdb.security.whitelist-ip-address=${CMDB_IP_WHITELISTS} \
${CUSTOM_PARAM} >>/data/wecmdb/log/wecmdb-core.log
```

2. 如果正确启动程序，正确的访问URL为：http://127.0.0.1:{your-port}/{your-context-path}

**Comment by royl88** [comment]
@jadeball 这个问题是否解决了呢？
