### ISSUE TITLE
mysql8支持

### ISSUE THREAD

**Issue by weihai4099** [WeBankPartners/we-cmdb#1182]
**描述您的需求**  
嗨，我们需要在arm上运行cmdb，但是mysql镜像只有8.0上才有arm版image。所以想问一下是否有计划升级到8.0.
我知道的需要改驱动类，jpa方言，驱动版本号。但是可能还有一些其他mysql5.6的特性。所以是否可以说明一下还有哪些坑。

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by royl88** [comment]
ARM平台目前我们没有办法进行实测呢，x86_64下是可以使用mysql 8.0版本的，还需要注意修改mysql 8.0的默认认证方式为：mysql_native_password，如果有其他问题，欢迎反馈。

**Comment by weihai4099** [comment]
确实是支持的，我刚测试了amd64的8.0是可以的，默认认证方式那个没有改，只改了hibernate的方言。是可以跑起来的
明天跑一下arm的

**Comment by weihai4099** [comment]
arm64 使用mysql/mysql-server:8.0 docker image 正常使用，没问题，已经验证

**Comment by manong123456** [comment]
你好，cmdb的ARM编译所需要的 ccr.ccs.tencentyun.com/webankpartners/golang-ext:v1.15.6 ccr.ccs.tencentyun.com/webankpartners/alpine-base:v1.0在哪里获取的呢，有ARM的编译指导吗
