### ISSUE TITLE
StateOperation 数据状态流转含义不明白

### ISSUE THREAD

**Issue by weihai4099** [WeBankPartners/we-cmdb#1186]
**描述您遇到的bug**  

页面将一条数据进行了确认，无法通过页面和接口将数据进行删除，请问该如何操作？
另外，
None("none"), Insert("insert"), Delete("delete"), Update("update"), Discard("discard"), Confirm("confirm"), 
Startup("startup"), Stop("stop");

这些状态的流转是什么样的，有什么特殊的业务规则么？ 可否简单说明一下
**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by royl88** [comment]
源码cmdb-wiki/docs下有关于项目的设计和使用说明，这里是状态流转说明在线链接：[CI状态机说明](https://github.com/WeBankPartners/we-cmdb/blob/master/cmdb-wiki/docs/developer/state_guide.md)

**Comment by weihai4099** [comment]
收到，感谢
