### ISSUE TITLE
代码中字段属性不判空。编辑报错

### ISSUE THREAD

**Issue by guanshen871** [WeBankPartners/we-cmdb#1190]
**描述您遇到的bug**  
![image](https://user-images.githubusercontent.com/37996974/102446521-f5d3b180-4068-11eb-9c04-6d38191a9039.png)
![image](https://user-images.githubusercontent.com/37996974/102446594-21569c00-4069-11eb-840d-e6dc5d3185f7.png)

**如何重现** 
进入系统-基础数据管理。选中一行编辑报错，发现we-cmdb/cmdb-ui/src/pages/admin/enums.vue中定义的table列中无查询需要的参数

**预期行为** 

**截图**  

**附加**

**Comment by royl88** [comment]
感谢反馈，经检查是由于支持历史数据autocomplete功能引发报错，虽然不影响此处的编辑保存功能的使用，但每次新增输入和编辑会弹出报错提示。
