### ISSUE TITLE
菜单权限里面的菜单显示问题

### ISSUE THREAD

**Issue by hchangfa** [WeBankPartners/we-cmdb#1193]
**描述您遇到的bug**  

**如何重现** 

**预期行为** 
![image](https://user-images.githubusercontent.com/32158491/102734524-fcb93780-437a-11eb-8251-e4c35ede1d99.png)

**截图**  

**附加**

**Comment by hchangfa** [comment]
枚举数据查询，枚举数据管理两个功能没法配置

**Comment by royl88** [comment]
感谢反馈，此处确实是“枚举数据查询”和“枚举数据管理”没有展示出来，安排。

**Comment by hchangfa** [comment]
如果需要自定义枚举目录，就没法从页面上做了。

**Comment by hchangfa** [comment]
如果新增枚举目录的话，就没法从页面做了。 @royl88

**Comment by royl88** [comment]
枚举菜单是比较早以前的版本遗留，当前版本已经被遗弃，所以
1. 基础数据里的枚举是提供给系统内部使用
2. 业务配置(即CI)中需要类似枚举的能力，可以直接通过新增CI或字段正则约束来实现，所以这个功能就没有再保留了。

**Comment by hchangfa** [comment]
好的，明白了，谢谢！
