### ISSUE TITLE
访问应用页面报错

### ISSUE THREAD

**Issue by hchangfa** [WeBankPartners/we-cmdb#1198]
**描述您遇到的bug**  
1.访问，首页 / 视图管理 / 应用架构设计
异常：Error
Can not find out CiType with given argument. (ciTypeId:37)
2.访问，首页 / 视图管理 / 应用部署设计
Error
Can not find out CiType with given argument. (ciTypeId:46)
**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by kanetz** [comment]
您好，请问您是在演示环境还是自己安装的环境遇到的这个问题？

**Comment by hchangfa** [comment]
您好，自己安装的环境 @kanetz

**Comment by hchangfa** [comment]
> 您好，请问您是在演示环境还是自己安装的环境遇到的这个问题？
您好，自己安装的环境 @kanetz

**Comment by kanetz** [comment]
我们正在尝试重现、验证和修复问题。

**Comment by kanetz** [comment]
@hchangfa 您好，根据我们的验证，猜测您在安装时采用了不带有模型数据的纯净CMDB方式。

在这种方式下，CMDB系统中没有倒入任何模型数据，然而现有“视图管理”菜单下的四个菜单项功能由于目前的代码问题，以硬编码的方式显式依赖了包含在[此压缩包](https://github.com/WeBankPartners/we-cmdb/releases/download/v1.5.5/wecmdb_model_init.zip)中的模型数据，所以导致无法正常工作。

我们将立即对此问题的修复方案进行评估并规划到后续的发布版本中。如果您想体验“视图管理”菜单下的功能，建议您将[此压缩包](https://github.com/WeBankPartners/we-cmdb/releases/download/v1.5.5/wecmdb_model_init.zip)中的模型数据以执行SQL脚本的方式倒入数据库。

谢谢！

**Comment by hchangfa** [comment]
@kanetz 您好，您猜的没错，我安装的时候采用了不带有模型数据的纯净CMDB方式。非常感谢您能回复。
