### ISSUE TITLE
筛选条件不支持ci属性的过滤规则

### ISSUE THREAD

**Issue by fanxianbin** [WeBankPartners/we-cmdb#1250]
筛选条件不支持ci属性的过滤规则，列表中会展示多余的数据，给用户造成一定的困扰，用户一旦选择过滤规则外的选项，将无法查询到数据，毕竟本身这个查询逻辑就是不正确的

**Comment by chaneyliu** [comment]
请在7月9日的版本修复。

**Comment by pobu168** [comment]
已修复，将随7月9日版本发布
