### ISSUE TITLE
CMDB日志查询的ciName和ciTypeName没有内容

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#144]
**描述您遇到的bug**  
CMDB日志查询的ciName和ciTypeName没有内容

**如何重现** 
1. 登录 http://111.230.161.237:8080/cmdb
2. 打开系统》日志查询页面，ciName和ciTypeName没有内容

**预期行为** 
CMDB日志查询的ciName和ciTypeName显示相应的内容

**截图**  
![image](https://user-images.githubusercontent.com/17095701/64493599-a70b6980-d2b4-11e9-9b45-13828e353f96.png)

**附加**

**Comment by chaneyliu** [comment]
先这样处理就可以。

**Comment by jordanzhangsz** [comment]
跟超哥同步过，解决方案如下：
1. 暂时去掉ciName和ciTypeName两列（数据库和页面展示）。
2. 日志内容支持模糊查询，一般用户都是通过他们自己录入的数据关键字进行模糊查询的，基本能满足大部分用户的查询需求。
