### ISSUE TITLE
建议枚举管理页面增加CI Type的信息

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#184]
**描述您的需求**  
建议枚举管理页面增加CI Type的信息，以便知道枚举是哪个CI Type下的，方便管理。

![image](https://user-images.githubusercontent.com/17095701/64931570-e107dd00-d86b-11e9-93d9-c985ef2a66d9.png)

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by irvinezhao** [comment]
reopen issue.

@zhangsenfeng  please fix typo ```共有枚举``` - >```公有枚举```

and add ```私有枚举``` 

code as below: 
```
_.cat.catType.catTypeName === "sys"
                ? "系统枚举"
                : _.cat.catType.catTypeName === "common"
                ? "公有枚举"
                : "私有枚举-" + _.cat.catType.catTypeName
```
