### ISSUE TITLE
CMDB初始化新的CMDB模型

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#191]
**描述您的需求**  
CMDB初始化脚本需要整理新的CMDB模型。

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by jordanzhangsz** [comment]
@chaneyliu @yolanda0209 新的CMDB模型需要落到初始化脚本，问一下从哪里导出新的CMDB模型？

**Comment by chaneyliu** [comment]
@jordanzhangsz ，在完全接管sandbox后CMDB初始化模型需要有做一下调整。预计10月中旬。

**Comment by jordanzhangsz** [comment]
@kanetz 桐哥，帮忙整理一下新的模型，我们想整理到初始化SQL里去，形成WeCMDB默认安装的最佳实践。

**Comment by jordanzhangsz** [comment]
新模型中文版schema已整理，但是无体验数据，等超哥准备wecube2.0版本体验数据的时候，一起处理。
