### ISSUE TITLE
日志查询的createdDate显示不是本地时间

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#192]
**描述您遇到的bug**  
日志查询的createdDate日期显示不是本地时间

**如何重现** 
1. 登录http://111.230.161.237:8080/cmdb/
2. 打开系统》日志查询，createdDate显示不是本地时间

![image](https://user-images.githubusercontent.com/17095701/65009603-d6b71300-d93f-11e9-9b7c-6da2e92abcf1.png)

**预期行为** 
日志查询的createdDate显示本地时间

**截图**  

**附加**

**Comment by jordanzhangsz** [comment]
Fixed at:
https://github.com/WeBankPartners/we-cmdb/pull/213
