### ISSUE TITLE
插件注册的CMDB属性配置由于长度太长导致保存失败

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#195]
**描述您遇到的bug**  

插件注册的CMDB属性配置由于长度太长导致保存失败。需修改数据库表
adm_integrate_template_alias_attr的key_name字段的长度。

![image](https://user-images.githubusercontent.com/17095701/65096056-31ab4180-d9f6-11e9-937e-fdfcd189047c.png)

![image](https://user-images.githubusercontent.com/17095701/65096076-4556a800-d9f6-11e9-86bf-aa683b11d4ab.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by jordanzhangsz** [comment]
Fixed at:
https://github.com/WeBankPartners/we-cmdb/pull/206
