### ISSUE TITLE
CMDB新增用户的密码管理

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#196]
**描述您的需求**  
1. 新增用户提供初始化随机密码
2. 用户用随机密码登录后可修改密码。

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by nevinxie** [comment]
这种通用的密码管理和登录，有没有开源组件？

**Comment by jordanzhangsz** [comment]
正在看KeePass能不能用...

**Comment by zhangsenfeng** [comment]
新增以下3个特性：
1. 新建用户时会为其生成随机密码，并提示用户保存；
2. 用户可在页面右上角用户名的下拉列表处修改个人密码；
3. 新增页面可以为其他用户重新生成随机密码，可通过菜单权限进行控制。
