### ISSUE TITLE
综合查询配置引用问题

### ISSUE THREAD

**Issue by zhangsenfeng** [WeBankPartners/we-cmdb#202]
**描述您遇到的bug**  
路由CI的两个属性都引用了安全区域，配置路由的综合查询时，只引用安全区域1，图上会同时出现安全区域1和安全区域2。连线只连到安全区域1，安全区域2无连线。

**如何重现** 
1. 登录 http://111.230.161.237:28080
2. 打开设计》综合查询管理页面，新增路由CI的综合查询，引用选择安全区域1。

**预期行为** 
只引用安全区域1，图上只有安全区域1。
引用安全区域1和安全区域2的连线正常显示,。

**截图**  
![image](https://user-images.githubusercontent.com/17095701/64399405-ed857c00-d09a-11e9-9a39-cac8b2a1c8a3.png)

**附加**

**Comment by irvinezhao** [comment]
issue fixed in #203
