### ISSUE TITLE
CMDB不能销毁已被关联的CI数据

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#207]
**描述您遇到的bug**  
CMDB不能销毁已被关联的CI数据。 

如该主机已经被运行实例关联，运行实例已经停止或销毁后。再点击“删除”按钮销毁主机，但是不允许销毁。

![image](https://user-images.githubusercontent.com/17095701/65139768-bff7e580-da3f-11e9-9bec-50af8496307a.png)

**如何重现** 

**预期行为** 
主机已经被运行实例关联，运行实例已经停止或销毁后。再点击“删除”按钮销毁主机，可以销毁主机。

**截图**  

**附加**

**Comment by nevinxie** [comment]
@chaneyliu 如果始终被关联，就不应该删除吧。这个需要超哥指导下

**Comment by chaneyliu** [comment]
1、所有关联主机的CI对象被删除或销毁，主机是可以被删除和销毁的。
2、关联CI对象删除销毁确认（confirm）后或同时，主机才可以被删除和销毁确认（confirm）。防止主机被销毁确认后，关联主机的CI在被恢复。
如果做不到2，至少需要做到1，如果存在2的情况发生，走异常处理流程。
