### ISSUE TITLE
建议增加提示信息以降低使用成本

### ISSUE THREAD

**Issue by zhangsenfeng** [WeBankPartners/we-cmdb#208]
**描述您的需求**  
在CI数据管理、CI数据查询页面中，增加简单的使用说明。
这样可以在保持原有设计的情况下，让用户更容易明白产品如何使用，降低学习成本。
举例如下：
![image](https://user-images.githubusercontent.com/26812573/65153121-cc8a3700-da5b-11e9-9fc5-b6534cb911cc.png)

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by nevinxie** [comment]
@irvinezhao 可以考虑使用教程技术。

**Comment by irvinezhao** [comment]
> @irvinezhao 可以考虑使用教程技术。

ok.

**Comment by irvinezhao** [comment]
@zhangsenfeng  看看这个 https://github.com/shipshapecode/shepherd

**Comment by zhangsenfeng** [comment]
这个的确比较好

**Comment by zhangsenfeng** [comment]
该问题与 #214 是同类问题，已按照 #214 的建议修改。
