### ISSUE TITLE
CI数据查询界面优化

### ISSUE THREAD

**Issue by citylin** [WeBankPartners/we-cmdb#214]
**描述您的需求**  
![image](https://user-images.githubusercontent.com/26247641/65245156-a37eaa80-db1e-11e9-81eb-384549462c55.png)
新手进来都不知道怎么进行CI数据查询，对这个提两点优化建议：
1、线上的关系描述文字[关联，属于]这些可以默认不展示，整体更清晰一些
2、当鼠标悬停到CI节点上时可以高亮该CI节点图标，关系线及关系描述文字（点击事件改为鼠标悬停事件）
3、单击CI节点就直接进行CI数据查询（双击查看一般人很难猜）
**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by zhangsenfeng** [comment]
该问题与 #208 是同类问题，目前 *CI数据查询* 及 *CI数据管理* 两个页面的操作不够直观，需要优化。

您的建议非常值得参考，我们会着重考虑。

**Comment by irvinezhao** [comment]
issue fixed in PR: #224
