### ISSUE TITLE
日志查询界面显示糟糕

### ISSUE THREAD

**Issue by nevinxie** [WeBankPartners/we-cmdb#217]
左边没有内容，空闲很大；右边的Log Content是最重要的，却显示很小。

![image](https://user-images.githubusercontent.com/3717486/65263467-4fd08900-db3f-11e9-97f6-f9f7b80e82ff.png)

**Comment by jordanzhangsz** [comment]
左边空的栏位已去掉，并优化了表头名称显示（把表头显示名称与数据关联的Key解耦），而且已支持Log Content内容的模糊查询。见:https://github.com/WeBankPartners/we-cmdb/pull/249

**Comment by irvinezhao** [comment]
> 左边空的栏位已去掉，并优化了表头名称显示（把表头显示名称与数据关联的Key解耦），而且已支持Log Content内容的模糊查询。见:#249

先通过这个方式优化显示，我会新建一个组件的优化来跟进列宽问题
