### ISSUE TITLE
编辑CI数据保存报错

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#222]
**描述您遇到的bug**  

CI Type运行实例有一个已销毁的多选枚举字段，编辑该CI数据再保存时报错。

![image](https://user-images.githubusercontent.com/17095701/65304240-bcd13680-dbb2-11e9-986e-2fd7c6f5808b.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by junchensz** [comment]
查询CI数据时，结果不返回已经"作废"的字段。
