### ISSUE TITLE
启动运行实例CI数据失败

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#238]
**描述您遇到的bug**  

启动运行实例CI数据失败。
![image](https://user-images.githubusercontent.com/17095701/65413747-ad592400-de24-11e9-965b-dcaadcec7375.png)

http://111.230.161.237:9090/cmdb/ci/state/operate?operation=startup
 [{"ciTypeId":"15","guid":"0015_0000000028"}]

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by junchensz** [comment]
Fixed in PR #250
