### ISSUE TITLE
MYSQL grant access issue when setting up local development

### ISSUE THREAD

**Issue by BenJaMiniature** [WeBankPartners/we-cmdb#254]
**描述您遇到的bug**  

![image](https://user-images.githubusercontent.com/52971115/65589984-92b9b300-dfbc-11e9-80bd-5202e14b1f46.png)

1) Got below error when running the 'grant' SQL.

0 | 3 | 15:31:52 | **grant all privileges on `wecmdb_dev`.* to 'wecmdb'@'%' identified by 'Abcd1234'** | Error Code: 1064. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'identified by 'Abcd1234'' at line 1 | 0.016 sec
-- | -- | -- | -- | -- | --
2) Got below error after removing 'identified by xxxx'

0 | 5 | 15:36:23 | **grant all privileges on `wecmdb_dev`.* to 'wecmdb'@'%'** | Error Code: 1410. You are not allowed to create a user with GRANT | 0.015 sec
-- | -- | -- | -- | -- | --

3) OK with SQL below.
**grant all privileges on `wecmdb_dev`.* to 'wecmdb'@'localhost';**

**如何重现** 
Run the command in a clean MYSQL.

**预期行为** 
grant command runs successfully.

**截图**  
![image](https://user-images.githubusercontent.com/52971115/65590874-132ce380-dfbe-11e9-9a14-fd80811b268b.png)

**附加**

**Comment by jordanzhangsz** [comment]
文档已做出调整，问题不存在。

本地模式，数据库采用H2, 不需要用户手动创建数据库。
如是已经存在的mysql数据库，用户把已存在数据库配置到application-dev.xml即可。
