### ISSUE TITLE
体验用户的名称

### ISSUE THREAD

**Issue by nevinxie** [WeBankPartners/we-cmdb#257]
体验用户已经被删除了Admin权限，不能管理用户。
用户名就别叫admin，容易混淆，建议叫一个简单的吧，例如test，或者wecmdb也可以。

**Comment by zhangsenfeng** [comment]
admin用户现在为CMDB管理员，目前没给**系统权限管理**及**CMDB模型管理**这两个菜单的权限。

另有一个用户为超级管理员。

**Comment by jordanzhangsz** [comment]
这个是角色命名问题，即数据使用问题，跟系统没关系。
