### ISSUE TITLE
有关联关系的两个CI删除的问题

### ISSUE THREAD

**Issue by zhangsenfeng** [WeBankPartners/we-cmdb#258]
**描述您遇到的bug**  
以 *调用时序设计* 及 *服务设计* 为例
如果 *调用时序设计* 中的一条数据A状态为*删除*，而 *服务设计* 中被关联的数据B未提交。此时删除 *服务设计* 中的B数据，查询 *调用时序设计* 中的数据A会报错。

**预期行为** 
对于该情景，有以下几种建议：
1. 数据B未提交时，数据A不能关联数据B；
2. 数据B未提交时，数据A不能提交；
3. 数据B未提交，且数据A状态为删除时（提交后删除），数据B不可删除；
4. 数据B未提交，删除数据B时，把数据A一并删除。

**截图**  
![image](https://user-images.githubusercontent.com/26812573/65659165-2b077480-e05d-11e9-8972-509024868c7c.png)
![image](https://user-images.githubusercontent.com/26812573/65659179-38246380-e05d-11e9-8d35-f9fe39d4fd95.png)

**附加**

**Comment by zhangsenfeng** [comment]
@chaneyliu 还请给个建议。

**Comment by jordanzhangsz** [comment]
这个算是个bug,对于删除有两种情况: 
1. 状态改变为终态（不同状态机其终态不同）2. 真正的数据库删除。

目前删除前的校验逻辑对这两种情况的处理是一样的，即如果存在被引用CI，且这些CI是终态，是可以删除当前CI的。

跟Gray对齐了下，这两种情况应分开校验，只有状态机决定是状态改为删除时，才需要判断被依赖CI的终态，否则校验被依赖CI是否存在即可。
