### ISSUE TITLE
表格默认按照创建时间降序排序

### ISSUE THREAD

**Issue by zhangsenfeng** [WeBankPartners/we-cmdb#261]
**描述您的需求**  
目前表格默认排序是按照创建时间升序排序，希望能默认按照默认排序。

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by jordanzhangsz** [comment]
这个可以在后端，面对UI的接口给个默认排序:如前端不给排序条件时，按“创建时间”倒序返回结果。

**Comment by jordanzhangsz** [comment]
Fixed at : https://github.com/WeBankPartners/we-cmdb/pull/286
