### ISSUE TITLE
查询用户菜单时，返回数据没有去重

### ISSUE THREAD

**Issue by zhangsenfeng** [WeBankPartners/we-cmdb#265]
**描述您遇到的bug**  
当一个用户同时为2个角色，且这两个角色配置了重复的菜单时，my-menus接口会返回重复的菜单数据。

**如何重现** 
1. 在权限管理中，选择两个不同的角色，分别添加admin用户
2. 同时给这两个角色同样的菜单权限
3. 刷新页面重新请求my-menus接口

**预期行为** 
希望my-menus返回的数据根据id去重

**截图**  
![image](https://user-images.githubusercontent.com/26812573/65750187-62981e80-e13a-11e9-88bb-7f0c2569d4cc.png)

**附加**

**Comment by irvinezhao** [comment]
Portal 没有此问题

**Comment by jordanzhangsz** [comment]
fixed at : https://github.com/WeBankPartners/we-cmdb/pull/287
