### ISSUE TITLE
CMDB本地H2启动后CI数据管理不现实CI关系图

### ISSUE THREAD

**Issue by nevinxie** [WeBankPartners/we-cmdb#273]
**描述您遇到的bug**  
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/3717486/65878902-b0728800-e3c1-11e9-9a6f-0f5881b6b41b.png">

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by jordanzhangsz** [comment]
Already fixed at issue #277, the corresponding PR is : https://github.com/WeBankPartners/we-cmdb/pull/280
