### ISSUE TITLE
新增调用时序设计CI数据失败

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#291]
**描述您遇到的bug**  
新增调用时序设计CI数据失败，提示error[null]。

Request URL: http://106.53.80.138/cmdb/ui/v2/ci-types/6/ci-data/batch-create
Request Method: POST
Payload：
[{"guid":"","r_guid":"","biz_key":null,"state":"","fixed_date":"","description":"aaa","code":"aaa","orchestration":223,"service_design":"0004_0000000007","name":"aaa","invoke_design_sequence":["0005_0000000009","0005_0000000007"]}]

**如何重现** 
1.打开CMDB Demo环境的菜单视图管理 / 应用架构设计
2.选择演示系统，点击“架构变更”
3.在调用时序设计新增CI数据保存失败

**预期行为** 
新增调用时序设计CI数据成功

**截图**  
![image](https://user-images.githubusercontent.com/17095701/66617338-4fd81c00-ec07-11e9-8ead-7859d71d92ba.png)

**附加**

**Comment by jordanzhangsz** [comment]
体验数据漏导入一张表adm_sequence导致，在线体验数据库已手工补了数据，并已永久fixed at : https://github.com/WeBankPartners/we-cmdb/pull/298
