### ISSUE TITLE
悬浮鼠标在物理部署图没有显示相应的描述

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#292]
**描述您遇到的bug**  
悬浮鼠标在物理部署图没有显示相应的描述。

**如何重现** 
1.打开CMDB Demo环境的菜单视图管理 / 应用部署设计
2.选择演示系统，生产环境查询物理部署图
3.悬浮鼠标在物理部署图的安全区域、资源集和主机上没有显示相应的描述，而是一串GUID

**预期行为** 
悬浮鼠标在物理部署图的安全区域、资源集和主机上显示相应的描述

**截图**  
![image](https://user-images.githubusercontent.com/17095701/66619700-73ec2b00-ec10-11e9-8482-3232aad0ef56.png)

**附加**

**Comment by zhangsenfeng** [comment]
fixed in #323
