### ISSUE TITLE
应用架构设计的物理部署图没有显示

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#293]
**描述您遇到的bug**  
应用架构设计的物理部署图没有显示

**如何重现** 
1.打开CMDB Demo环境的菜单视图管理 / 应用架构设计
2.选择演示系统，点击“架构变更”
3.在物理部署图页面没有显示图

**预期行为** 
应用架构设计的物理部署图可以正常显示

**截图**  

![image](https://user-images.githubusercontent.com/17095701/66620671-e579a880-ec13-11e9-9b1c-ca89057488bf.png)

**附加**

**Comment by zhangsenfeng** [comment]
fixed in #323
