### ISSUE TITLE
IDC资源规划和IDC规划设计的CI数据显示没有根据选择的IDC过滤

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#295]
**描述您遇到的bug**  
IDC资源规划和IDC规划设计的CI数据显示没有根据选择的IDC过滤

**如何重现** 
1.打开CMDB Demo环境的菜单视图管理 / IDC资源规划 ，视图管理 / IDC规划设计 
2.选择IDC进行查询
3.切换到CI数据查看，CI数据显示没有根据选择的IDC过滤

**预期行为** 
IDC资源规划和IDC规划设计的CI数据显示根据选择的IDC过滤

**截图**  

![image](https://user-images.githubusercontent.com/17095701/66620805-6e90df80-ec14-11e9-820c-663a2cbfd2a7.png)

**附加**

**Comment by jordanzhangsz** [comment]
这个过滤功能原来wecube没有开发，这里需要额外进行开发。

**Comment by zhangsenfeng** [comment]
@jordanzhangsz 后端完成后麻烦assign回给我，保持assignment只有一个人

**Comment by zhangsenfeng** [comment]
Fixed in #423
