### ISSUE TITLE
应用部署设计的物理部署图显示了与选定的环境不相关的图

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#296]
**描述您遇到的bug**  
应用部署设计的物理部署图显示了与选定的环境不相关的图

**如何重现** 
1.打开CMDB Demo环境的菜单视图管理 / 应用部署设计
2.选择演示系统，STGk环境
3.查看物理部署图，STGk环境未配置相应的部署数据，却显示了与该环境不相关的物理部署图

**预期行为** 
应用部署设计的物理部署图不应显示与选定的环境不相关的图

**截图**  
![image](https://user-images.githubusercontent.com/17095701/66621011-2aeaa580-ec15-11e9-93fd-ad1841984b58.png)

**附加**

**Comment by zhangsenfeng** [comment]
STGk环境未配置任何子系统，但查询物理部署图时，仍返回了数据，还请 @jordanzhangsz  定位一下问题。
