### ISSUE TITLE
应用部署设计切换选择的系统和环境进行查询，相应的CI数据没有更新显示

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#297]
**描述您遇到的bug**  
应用部署设计切换选择的系统和环境进行查询，相应的CI数据没有更新显示

**如何重现** 
1.打开CMDB Demo环境的菜单视图管理 / 应用部署设计
2.选择演示系统，STGi环境进行查询
3.查看子系统的CI数据
4.切换选择的系统和环境进行查询，相应的CI数据没有更新显示

**预期行为** 
应用部署设计切换选择的系统和环境进行查询，相应的CI数据应更新显示

**截图**  

![image](https://user-images.githubusercontent.com/17095701/66621688-a5b4c000-ec17-11e9-95bc-8478a3b221e7.png)

**附加**

**Comment by zhangsenfeng** [comment]
fixed in #324
