### ISSUE TITLE
部署物理图的底色、字体颜色及字体大小需要调整

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#299]
**描述您遇到的bug**  
部署物理图的底色、字体颜色及字体大小需要调整。有些文字与底色混淆在一起，不易查看。

![image](https://user-images.githubusercontent.com/17095701/66623053-a00da900-ec1c-11e9-808c-0feb6d8a7c7a.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by zhangsenfeng** [comment]
fixed in #323
