### ISSUE TITLE
应用架构设计去定版后CI数据没有刷新

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#300]
**描述您遇到的bug**  
应用架构设计确认定版后CI数据没有刷新。

![image](https://user-images.githubusercontent.com/17095701/66623385-047d3800-ec1e-11e9-9910-68cdacc9fc47.png)

![image](https://user-images.githubusercontent.com/17095701/66623398-12cb5400-ec1e-11e9-8a97-6efa00dee6e3.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by zhangsenfeng** [comment]
fixed in #325
