### ISSUE TITLE
“”应用架构设计“”页面切换“”调用时序设计“”时当前调用的信息没有更新

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#304]
**描述您遇到的bug**  
“”应用架构设计“”页面切换“”调用时序设计“”时当前调用的信息没有更新，仍保留前一个调用时序设计的调用信息。

![image](https://user-images.githubusercontent.com/17095701/66697517-e4767300-ed08-11e9-986e-b391f350970e.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by zhangsenfeng** [comment]
fixed in #412

**Comment by zhangsenfeng** [comment]
选择调用时序设计后，再切换系统设计，调用时序设计的信息没有更新

**Comment by zhangsenfeng** [comment]
Fixed in #443
