### ISSUE TITLE
用户登录过期后刷新页面没有跳转到登录页面

### ISSUE THREAD

**Issue by xuxuzhesi** [WeBankPartners/we-cmdb#306]
**描述您的需求**  
用户登录过期后刷新页面，报错，提示Login user not found。
不应该报错，可以给个提醒，然后跳转到登录页面

**预期行为**  
用户登录过期，给个提醒，然后跳转到登录页面

**描述您考虑过的替代方案**  

**附加**
![error_1](https://user-images.githubusercontent.com/27829483/66697771-53ed6200-ed0b-11e9-9f8f-ca4abcb25d8c.png)

**Comment by zhangsenfeng** [comment]
fixed in #337
