### ISSUE TITLE
【国际化】README支持中英双语

### ISSUE THREAD

**Issue by jordanzhangsz** [WeBankPartners/we-cmdb#307]
【国际化】README支持中英双语

**Comment by irvinezhao** [comment]
起草了一下README支持中英双语的做法，代码在分支307_support_cn_en_readme，大家可以一起讨论

**Comment by jordanzhangsz** [comment]
好的，多谢Irving, 我会继续在这个分支上进行readme的英文翻译。

**Comment by jordanzhangsz** [comment]
感谢Irving和桐哥帮忙
