### ISSUE TITLE
系统权限管理页面增加用户登录名的信息

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#322]
**描述您的需求**  
当前系统权限管理页面的用户显示了用户全名和用户描述信息，无用户登录名的信息，建议增加用户登录名的信息。
![image](https://user-images.githubusercontent.com/17095701/66730718-06493480-ee86-11e9-8ce6-b9e6e3b427c5.png)

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by jordanzhangsz** [comment]
@zhangsenfeng 这个问题昨天你是在另外一个issue解决了是吗？

**Comment by zhangsenfeng** [comment]
> @zhangsenfeng 这个问题昨天你是在另外一个issue解决了是吗？

是的，以前是fullname(description)，现在已改为username(description)
