### ISSUE TITLE
同步Release信息及jar包至Gitee

### ISSUE THREAD

**Issue by jordanzhangsz** [WeBankPartners/we-cmdb#332]
**描述您的需求**  
目前我们只同步了Issues/Comments至gitee,  需要把release的信息及jar包也进行自动同步。

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by jordanzhangsz** [comment]
**目前的方案：**
方式：定时同步
范围：WeBankPartners下所有的repositories  - 1) 代码  2) issue(以json的方式存放在GiteeBackup下)  3).issue comments

**建议方案：**
方式：通过github上面的hook, 定制触发条件，直接调用gitee的API进行实时同步
范围：WeBankPartners下所有的repositories  
内容：
1) 代码 
2) issue (直接在repository下同步issues)   
3) issue comments(直接在repository下同步issues)  
4) Release Notes/Release artifects

> 同时把gitee备库设为只读，WeCMDB随v1.3版本对外开放。

**Comment by irvinezhao** [comment]
@xuxuzhesi 
11.11：
1、#332 同步Release信息及jar包至Gitee

11.12：
1、#332 同步Release信息及jar包至Gitee

**Comment by xuxuzhesi** [comment]
1、 Release信息可以同步到gitee，通过pythn脚本调用github API获取github指定仓库的releases信息，组装参数调用gitee API 新增release。因gitee没有相关API，jar包无法同步到gitee。
 2.、issue信息同步到gitee，通过调用gitee API新增issue，目前存在问题：
   - gitee创建issues的API不能指定用户信息，gitee通过token获取用户信息，导致issue创建人固定，不能和github同步
   - gitee创建指定issue下的comment的API不能指定用户信息，同issue
   - gitee创建issues的API不能指定ID，也无其他唯一字段，导致gitee的issue无法跟github的issue相关联，无法判断哪些issue是新增的
   - github的issue的操作记录无法同步，因gitee无修改操作记录相关API
> 综上原因，issue的同步不做修改
