### ISSUE TITLE
text类型属性支持正则校验做自定义格式约束

### ISSUE THREAD

**Issue by chaneyliu** [WeBankPartners/we-cmdb#34]
CMDB模式设计，“text”类型的属性，支持添加一段正则表达式，做自定义格式校验。
第一步先做前端校验，后继可以考虑增加后端校验。

![image](https://user-images.githubusercontent.com/54091452/63338375-4227b800-c375-11e9-840d-6ca9e56045a0.png)

**Comment by jordanzhangsz** [comment]
后端校验：https://github.com/WeBankPartners/we-cmdb/pull/262
