### ISSUE TITLE
CMDB模型设计过滤规则不支持多选枚举

### ISSUE THREAD

**Issue by chaneyliu** [WeBankPartners/we-cmdb#350]
**描述您遇到的bug**  
CMDB模式设计，过滤规则配置，不支持多选枚举的配置。选到多选枚举列后，不会弹出后继的codeid、code、value等选择框。
1、资源集合设计的“集群类型”属性是对选枚举。
![image](https://user-images.githubusercontent.com/54091452/67189702-4c237100-f421-11e9-98f7-92f9b4816c4a.png)
2、在“服务设计”的“集群类型”属性过滤规则配置时，到了“集群类型”后 ，就没有后继的弹出了。
![image](https://user-images.githubusercontent.com/54091452/67189848-8bea5880-f421-11e9-8c45-d5c12df6ad9e.png)

同时多选引用可以配置，但是请评估后台是否支持过滤规则的运行。

**如何重现** 
在UAT环境可以重新。

**预期行为** 
配置和使用过滤规则，支持多选枚举和多选引用。

**截图**  

**附加**

**Comment by chaneyliu** [comment]
![image](https://user-images.githubusercontent.com/54091452/67191150-bb01c980-f423-11e9-8375-1828313e697c.png)

**Comment by zhangsenfeng** [comment]
fixed in #374
