### ISSUE TITLE
修改wecmdb的url

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#355]
**描述您的需求**  
在sanbox上部署wecmdb的demo环境，域名为https://sandbox.webank.com/wecmdb， 需要wecmdb修改url：从http://x.x.x.x/cmdb/ 改成 http://x.x.x.x/wecmdb/ 

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by jordanzhangsz** [comment]
Fixed at : https://github.com/WeBankPartners/we-cmdb/pull/358

@yolanda0209 温馨提示下，这个改动部署会影响wecube, 因为wecube配置了这个URL连接CMDB, 所以需要跟wecube的改动一起部署。
