### ISSUE TITLE
新增枚举保存console报错

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#362]
**描述您遇到的bug**  
在CMDB模型管理新增CI Type后，再新增枚举保存不了，console报错。

![image](https://user-images.githubusercontent.com/17095701/67375739-a9e8c200-f5b5-11e9-846d-c4572acbb535.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by zhangsenfeng** [comment]
在修复其他问题之后，该问题已无法重现。
