### ISSUE TITLE
CI Data删除操作没有记录日志

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#366]
**描述您遇到的bug**  
CI Data删除操作没有记录日志。删除成功或失败都没有记录日志。
![image](https://user-images.githubusercontent.com/17095701/67469420-c3a20c00-f67e-11e9-97bb-035f16824636.png)
![image](https://user-images.githubusercontent.com/17095701/67469455-cf8dce00-f67e-11e9-8222-85c6b009ed24.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by xuxuzhesi** [comment]
Fixed at 
https://github.com/WeBankPartners/we-cmdb/pull/337
