### ISSUE TITLE
Make build container name can be configurable

### ISSUE THREAD

**Issue by junchensz** [WeBankPartners/we-cmdb#370]
**描述您的需求**  
When build job is lunched in jenkins, error will happen if there is a same name container running.
The container name need be configurable, each job need have unique build container name to avoid error.

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by jordanzhangsz** [comment]
Good to see raising the issue in english, it remind us one thing, we need to adjust the issue template with titles for supporting english as well.
