### ISSUE TITLE
CMDB综合查询管理页面更新综合查询console报错

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#375]
**描述您遇到的bug**  

CMDB综合查询管理页面更新综合查询console报错.
![image](https://user-images.githubusercontent.com/17095701/67667083-0da12f80-f9a8-11e9-9ff0-dddb4b93fc62.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by zhangsenfeng** [comment]
fixed in #379
