### ISSUE TITLE
CMDB提供动态模型查询接口，并在注册XML内声明

### ISSUE THREAD

**Issue by chaneyliu** [WeBankPartners/we-cmdb#376]
**描述您的需求**  
CMDB存在动态模型能力。在首次注册初始化模型后，用户会在对数据模型做变更，CMDB需要提供一个模型查询接口，返回内容格式与XML定义的datamodel格式一致。对于删除的数据模型数据，建议也返回并提供一个状态字段标记。这个接口在XML定义的datamodel内声明，供WeCube解析并同步数据模型使用。

**预期行为**  
1、有一个同步接口。
2、在XML内声明。

**描述您考虑过的替代方案**  
无
**附加**
无

**Comment by jordanzhangsz** [comment]
WeCMDB插件在wecube-plugins-wecmdb仓库开发，本需求及其实现请参见：https://github.com/WeBankPartners/wecube-plugins-wecmdb/issues/14
