### ISSUE TITLE
综合查询没有显示表头和数据

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#385]
**描述您遇到的bug**  
综合查询没有显示表头和数据。
![image](https://user-images.githubusercontent.com/17095701/67925345-0e2b0780-fbee-11e9-914d-a29f00765318.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by zhangsenfeng** [comment]
fixed in #390
