### ISSUE TITLE
综合查询的下拉框排列不整齐

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#387]
**描述您遇到的bug**  
综合查询的下拉框排列不整齐。
![image](https://user-images.githubusercontent.com/17095701/67925614-d4a6cc00-fbee-11e9-8b7f-0f8fcc2c9b47.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by zhangsenfeng** [comment]
fixed in #395
