### ISSUE TITLE
应用架构设计新增调用时序设计报错

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#389]
**描述您遇到的bug**  
应用架构设计新增调用时序设计报错，时序图不能显示。
![image](https://user-images.githubusercontent.com/17095701/67927202-f7d37a80-fbf2-11e9-819e-e38be77098cf.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by jordanzhangsz** [comment]
@zhangsenfeng 前端语法错误，帮忙看看

**Comment by zhangsenfeng** [comment]
fixed in #401
