### ISSUE TITLE
应用部署设计“应用树状逻辑图”展示的层名称和展示的图形内容不一致

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#418]
**描述您遇到的bug**  
应用部署设计“应用树状逻辑图”展示的层名称和展示的图形内容不一致。 如层描述为“Service” ，而图形展示了Service + Running Instance。

![image](https://user-images.githubusercontent.com/17095701/68285705-ba6f6100-00ba-11ea-9829-207cc80edf19.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by zhangsenfeng** [comment]
Fixed in #446
