### ISSUE TITLE
应用部署设计“应用逻辑图“展示问题

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#420]
**描述您遇到的bug**  
应用部署设计“应用逻辑图“展示问题：
1. 应用逻辑图显示了重复的单元“APP”，没有显示运行实例
2. 应用逻辑图显示空格子
![image](https://user-images.githubusercontent.com/17095701/68287478-c1e43980-00bd-11ea-8073-af1e94a054b9.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by zhangsenfeng** [comment]
Fixed in #482
