### ISSUE TITLE
应用部署设计页面查询主机无数据返回

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#421]
**描述您遇到的bug**  
应用部署设计页面应用逻辑图有主机信息，但是查询主机无数据返回。

![image](https://user-images.githubusercontent.com/17095701/68287716-230c0d00-00be-11ea-9f31-a9c634684cbb.png)
![image](https://user-images.githubusercontent.com/17095701/68287813-4931ad00-00be-11ea-9472-dd86ddd7d7e5.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by xuxuzhesi** [comment]
主机数据本来时没有的，应用部署图有问题

**Comment by xuxuzhesi** [comment]
主机数据没问题，主机数据需要根据资源集-单元关联，所选条件应该是没有数据的，应用逻辑图有问题
