### ISSUE TITLE
CMDB模型管理的CI属性操作按钮错位导致无法操作

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#425]
**描述您遇到的bug**  
CMDB模型管理的CI属性操作按钮错位
![image](https://user-images.githubusercontent.com/17095701/68351846-a3268700-013f-11ea-8638-2094cd5bfa0b.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by zhangsenfeng** [comment]
Fixed in #438
