### ISSUE TITLE
新增枚举数据时枚举组字段无下拉数据

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#427]
**描述您遇到的bug**  
新增枚举数据时枚举组字段无下拉数据。
![image](https://user-images.githubusercontent.com/17095701/68356823-4f6f6a00-014e-11ea-8866-5a69d4831cb3.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by zhangsenfeng** [comment]
Fixed in #436
