### ISSUE TITLE
CMDB显示语言为英文但是菜单和页面为中文

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#428]
**描述您遇到的bug**  
CMDB显示语言为英文但是菜单和页面为中文。
![image](https://user-images.githubusercontent.com/17095701/68357779-5e0b5080-0151-11ea-97cd-6b3195c54baa.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by zhangsenfeng** [comment]
国际化是用了浏览器的本地缓存。
该问题是因为同一浏览器开了多个CMDB，每个页签选择了不同的语言，导致缓存互相影响。
