### ISSUE TITLE
CMDB中英文切换时菜单不更新

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#440]
**描述您遇到的bug**  
在苹果手机、ipad终端和苹果电脑的safari浏览器访问CMDB中英文切换时菜单不更新。

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by zhangsenfeng** [comment]
safari浏览器兼容性问题。

**Comment by zhangsenfeng** [comment]
Fixed in #441
