### ISSUE TITLE
错误提示信息用ci type id或code id提示不清晰

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#466]
**描述您的需求**  
错误提示信息用ci type id或code id提示不清晰，需要查数据库才知道是哪个ci type或属性，建议用名称。
![image](https://user-images.githubusercontent.com/17095701/64509685-d781f080-d312-11e9-9c7f-895eaf9d217e.png)

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by jordanzhangsz** [comment]
@xuxuzhesi 这个作为一类问题进行处理，把wecmdb的日志梳理一遍，看到这种id的，顺带把名称也输出一下。
