### ISSUE TITLE
删除CMDB数据模型层时浏览器控制台出现JS错误

### ISSUE THREAD

**Issue by kanetz** [WeBankPartners/we-cmdb#467]
**描述您遇到的bug**  

**如何重现** 

**预期行为** 

**截图**  
![image](https://user-images.githubusercontent.com/1160645/69318494-3dc2b200-0c78-11ea-9c56-cad7c07518c7.png)

**附加**

**Comment by zhangsenfeng** [comment]
@kanetz 这个问题是cmdb 的问题，目前以将该issue放到cmdb仓库下，并且该问题已修复。
