### ISSUE TITLE
保存CI数据接口返回错误但是UI没有错误信息提示

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#471]
**描述您遇到的bug**  
保存CI数据接口返回错误但是UI没有错误信息提示。
![image](https://user-images.githubusercontent.com/17095701/69522931-94dcc580-0f9d-11ea-8fe9-e4ad7faa958c.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by zhangsenfeng** [comment]
该问题与 #474 是同一个bug引发的，现已修复。
