### ISSUE TITLE
打开CI Type数据报错

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#472]
**描述您遇到的bug**  
打开CI Type数据报错。
![image](https://user-images.githubusercontent.com/17095701/69609154-d89a0280-1063-11ea-8951-5124b5cc8d00.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by jordanzhangsz** [comment]
这个是环境配置的问题， wecmdb插件连接wecmdb不通引起，已解决。
