### ISSUE TITLE
编辑某CI提交后页面会跳转到其他CI

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#479]
**描述您遇到的bug**  
编辑某CI提交后页面会跳转到其他CI。如给资源实例新增一个属性提交后，页面跳转到IP地址。
![image](https://user-images.githubusercontent.com/17095701/69704320-1f542f00-112e-11ea-81f4-28221e1af36b.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by jordanzhangsz** [comment]
前端问题，森锋帮忙处理一下 @zhangsenfeng

**Comment by zhangsenfeng** [comment]
这个问题已于 #508 一同解决。
