### ISSUE TITLE
设置填充规则后未按预期级联触发属性值的更新

### ISSUE THREAD

**Issue by kanetz** [WeBankPartners/we-cmdb#484]
**描述您遇到的bug**  

**如何重现** 
设计 - CI Data Management

**预期行为** 

**截图**  
![image](https://user-images.githubusercontent.com/1160645/69404831-37483f00-0d39-11ea-8066-b676c55d7116.png)

![image](https://user-images.githubusercontent.com/1160645/69404885-5050f000-0d39-11ea-8e11-40c8d09b0160.png)

![image](https://user-images.githubusercontent.com/1160645/69404950-7aa2ad80-0d39-11ea-9b16-c51f5c5b78b0.png)

**附加**

**Comment by jordanzhangsz** [comment]
问题暂时无法重现，如出现另外提issue再处理
