### ISSUE TITLE
编辑CI数据时部分字段不回显原值

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#493]
**描述您遇到的bug**  
编辑CI数据时部分字段不回显原值。
![image](https://user-images.githubusercontent.com/17095701/69943840-d0890980-1520-11ea-92f5-dc90f092d6a9.png)

![image](https://user-images.githubusercontent.com/17095701/69943866-e1d21600-1520-11ea-9bcb-b3139112273a.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by jordanzhangsz** [comment]
@zhangsenfeng 这个问题帮忙定位一下？

**Comment by zhangsenfeng** [comment]
![image](https://user-images.githubusercontent.com/26812573/75404931-03d40c80-5947-11ea-9b7e-9e9a670080fd.png)
@yolanda0209
