### ISSUE TITLE
编辑枚举保存后catid错乱

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#501]
**描述您遇到的bug**  
编辑枚举保存后catid错乱， 如编辑catid=40的枚举，保存后catid变成1。
![image](https://user-images.githubusercontent.com/17095701/69792771-32383380-1202-11ea-9188-0a461abc144c.png)
![image](https://user-images.githubusercontent.com/17095701/69792819-4714c700-1202-11ea-9004-42534e2fb948.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by zhangsenfeng** [comment]
前端传值正确，保存后catid变为1，这是后台的问题，麻烦思哲看一下。 @xuxuzhesi

**Comment by jordanzhangsz** [comment]
@xuxuzhesi 这个问题处理了吗？

**Comment by xuxuzhesi** [comment]
@jordanzhangsz 已解决 @yolanda0209 测试过，dev分支，和当吃更改枚举唯一约束一起提交的代码 #490 Fix the enum update
