### ISSUE TITLE
CMDB放弃CI数据的编辑失败

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#517]
**描述您遇到的bug**  
CMDB放弃CI数据的编辑失败。

![image](https://user-images.githubusercontent.com/17095701/70765991-66c9f480-1d97-11ea-975e-28431f166542.png)

![image](https://user-images.githubusercontent.com/17095701/70765949-4863f900-1d97-11ea-9807-0ddda6d6f238.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by jordanzhangsz** [comment]
这是UAT的初始化数据有问题引起，ADM_CI_TYPE_ATTR_BASE的数据重新刷一下，已解决。
