### ISSUE TITLE
变量替换 - 密码加解密处理

### ISSUE THREAD

**Issue by jordanzhangsz** [WeBankPartners/we-cmdb#528]
**描述您的需求**  
一台资源服务器被创建出来后，密码会被加盐加密存储至某个CI上（如资源实例）
当一个应用部署的时候，需要去连接这个资源实例(如mysql), 就需要获取其加过密的password和盐信息，也就是说同一个变量，需要获取一种以上的信息。如盐信息guid

**预期行为**  
变量替换填充时，支持一个变量可以填充一种以上信息。
如password这个变量需要携带guid

**Comment by jordanzhangsz** [comment]
为了避免界面用户输入的数据和系统使用的分隔符冲突，造成解析错误，特考虑使用ASCII码为0x01的字符，这个字符用户键盘无法输入，较为安全。

用于变量替换的解析规则定义如下：

**语法规则：**

前端显示：
hostname, port, password& guid = redis, 8080, MD5XXX& 0015_0000000001

后端交互：hostname,0x01port,0x01password&0x01guid0x01=0x01redis,0x018080,0x01MD5XXX&0x010015_0000000001

**说明：**
1. ‘0x01=0x01’用于变量名串与变量值串的分割
2. ‘,0x01’用于不同变量名和值的分割
3. ‘&0x01’用于同一变量名与附带信息的分割

如有疑问，请反馈，谢谢。

**Comment by xuxuzhesi** [comment]
@brankbao 
变量替换功能出参， 0x01为键盘不可录入的特殊符号，表现形式为空格，变量env,httpport,appname取相应值，变量password需要获取密码和该密码的guid，”业务应用实例“ 的属性 “差异变量值” 填充的值如下：
env,0x01httpport,0x01appname,0x01password=TestUnit12,0x018080,0x01TestSystemDesign_STGi_TestSubsystem_TestUnit_deploy_smoke,0x01123&0x01guid
