### ISSUE TITLE
新版本的Wecube还是能在CI数据管理看到两个同名表

### ISSUE THREAD

**Issue by DeliaDing123** [WeBankPartners/we-cmdb#535]
**描述您遇到的bug**  
新版本的Wecube还是能看到两个机房键。

**如何重现** 
选择CI数据管理-》快速点击机房两次。

**预期行为** 
正常点击两次应该也只会出现一次。

**截图**  
![image](https://user-images.githubusercontent.com/46696471/66561476-2037fe00-eb8c-11e9-8277-5b181d92c697.png)

**附加**

**Comment by irvinezhao** [comment]
duplicate with #497
