### ISSUE TITLE
WeCMDB支持历史数据查询

### ISSUE THREAD

**Issue by jordanzhangsz** [WeBankPartners/we-cmdb#538]
**描述您的需求**
为了满足用户对CMDB数据的多维度查询需求，需要增强我们的API接口，支持对历史数据的多功能查询，如可按某个fixed_date进行查询，查出该fixed_date当时的所有CI的状态，供API使用方进行按需展示

**预期行为**
1. 输入指定fixed_date，可查单个CI的数据状态
2. 输入指定fixed_date，可查多个CI(综合查询）的数据状态

**Comment by jordanzhangsz** [comment]
跟超哥对齐了一下，除了上面的1，2两点，根据fixed_date查CI外，还需支持：

3. CMDB的数据查询接口，有一个参数控制查询：
         时间：查询条件增加update time < 时间。
         类型1: 返回r_guid一样的最新一条纪录。并在此基础上加过滤条件。
         类型2: 返回r_guid一样的最新一条confirm且非删除状态的的纪录，并在此基础上加过滤条件。（当前现实）
         类型3: 返回所有纪录，包括历史纪录。

对应前端，可以在查询和管理图形的上面增加一个“时间选择”和“查询类型选择”的条件输入框。并在后继的查询提示在右上角。

**Comment by jordanzhangsz** [comment]
类型名称：
1. 最新
2. 现实
3. 所有

**Comment by zhangsenfeng** [comment]
示意图
![image](https://user-images.githubusercontent.com/26812573/71407571-60305c80-2676-11ea-9809-89cfdb69dfdf.png)
