### ISSUE TITLE
WeCMDB增加版本对比功能

### ISSUE THREAD

**Issue by jordanzhangsz** [WeBankPartners/we-cmdb#558]
**作为** WeCMDB用户
**我想要** 在CI数据更新保存后，查看我本次更新对比原来的数据，做了哪些具体更新
**从而** 能够在确认之前，再次确定我的更新是我想要的

方案：
1. 在CI数据操作区，增加一个按钮“对比”
2. 调用后端接口，查找出本行数据及上一版本的数据
3. 前端弹框展示这两个版本的差异，以颜色高亮区分改动部分

**Comment by xuxuzhesi** [comment]
@jordanzhangsz @zhangsenfeng @ElliotShi 该需求可以通过原查询接口实现，例：
/ui/v2/ci-types/{ci-type-id}/ci-data/query
通过拼装参数的QueryRequest的Filters实现查询
{
	"dialect": {
		"showCiHistory": true
	},
	"filters": [
		{
			"name": "guid",
			"operator": "in",
			"value": [
				"当前数据guid",
				"当前数据p_guid"
			]
		}
	]
}
