### ISSUE TITLE
WeCMDB前端适应新模型调整

### ISSUE THREAD

**Issue by jordanzhangsz** [WeBankPartners/we-cmdb#562]
**作为** WeCMDB的用户
**我想要** 对视图做如下几点调整

- [x] 1. 页面顶部的下拉框改为根据 **系统** 做筛选，如下图所示：

![image](https://user-images.githubusercontent.com/26812573/71946675-78bb7d80-3205-11ea-9bb0-6d3aad515fc2.png)

- [x] 2. **应用逻辑图** 从外层到内层分别需要展示以下节点：**系统** > **子系统** > **单元** > **业务运行实例** ，其中 **单元** 下如果有 **业务运行实例** ，则需要展示 **业务运行实例** 对应的code、url及ip，如下图显示：

![image](https://user-images.githubusercontent.com/26812573/71946411-b79d0380-3204-11ea-9285-1b69e2398644.png)

- [x] 3. **应用逻辑图** 需要展示 **调用** 关系

- [x] 4. **应用树状逻辑图** 需要正常展示

- [x] 5. 该页面下的ci数据管理需要根据所选系统做过滤

- [x] 6. **物理部署图** 需要适应新模型

**从而** 更好的图形化展示新模型的配置信息及其关系

**Comment by zhangsenfeng** [comment]
### 应用部署设计页面需要适应新模型，需要以下几点改动：
1. 页面顶部的下拉框改为根据 **系统** 做筛选，如下图所示：
![image](https://user-images.githubusercontent.com/26812573/71946675-78bb7d80-3205-11ea-9bb0-6d3aad515fc2.png)
2. **应用逻辑图** 从外层到内层分别需要展示以下节点：**系统** > **子系统** > **单元** > **业务运行实例** ，其中 **单元** 下如果有 **业务运行实例** ，则需要展示 **业务运行实例** 对应的code、url及ip，如下图显示：
![image](https://user-images.githubusercontent.com/26812573/71946411-b79d0380-3204-11ea-9285-1b69e2398644.png)
3. **应用逻辑图** 需要展示 **调用** 关系
4. **应用树状逻辑图** 需要正常展示
5. 该页面下的ci数据管理需要根据所选系统做过滤
6. **物理部署图** 需要适应新模型

**Comment by zhangsenfeng** [comment]
物理部署图未完成
