### ISSUE TITLE
CI数据由于pguid缺失导致“放弃”操作失败

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#576]
**描述您遇到的bug**  
CI数据由于pguid缺失导致“放弃”操作失败。

![image](https://user-images.githubusercontent.com/17095701/71441134-2aa17700-273b-11ea-9118-2d9755529ed9.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by xuxuzhesi** [comment]
@yolanda0209  在出现问题的数据库执行一条更新sql：
update adm_ci_type_attr c set c.is_refreshable = 0 where c.property_name = 'p_guid';
