### ISSUE TITLE
CI根据确认日期过滤查询报错

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#579]
CI的确认日期为text类型，不易输入日期和时间，查询报错。
![image](https://user-images.githubusercontent.com/17095701/71452961-d8586880-27c3-11ea-801f-a9d9f5301a3c.png)

**Comment by chaneyliu** [comment]
确认日期为text有特殊考虑。
1.5.0版本已修复查询报错
