### ISSUE TITLE
英文页面的样式和字段显示名称问题 

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#580]
**描述您遇到的bug**  
CI综合查询管理英文页面的字段命名问题 ：
1. integrated_query_name 应改为 Integrated Query Name
![image](https://user-images.githubusercontent.com/17095701/71453035-40a74a00-27c4-11ea-8b11-c50001784afa.png)
2. Attribute 应 改为 Attributes，reference_to 和 reference_by不是词语。
![image](https://user-images.githubusercontent.com/17095701/71453212-1f932900-27c5-11ea-8a59-d2f9c2ee8205.png)

综合查询页面显示问题。

1. 字段底色为黑色看不清字
2. 字段和按钮的名称大小写还有下划线
![image](https://user-images.githubusercontent.com/17095701/71453489-73ead880-27c6-11ea-84c1-2bccdc8efb98.png)

*如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by jordanzhangsz** [comment]
该问题与 #565重复，统一使用 #565 解决
