### ISSUE TITLE
编辑“资源实例”CI数据的“主资源实例“保存报错

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#582]
**描述您遇到的bug**  
编辑“资源实例”CI数据的“主资源实例“保存报错。
![image](https://user-images.githubusercontent.com/17095701/71454002-700c8580-27c9-11ea-84e4-aa74cb68cd40.png)

Request URL: http://111.230.161.237:19090/wecmdb/ui/v2/ci-types/15/ci-data/batch-update
Request Method: POST
Payload：
[{"end_date":"","charge_type":77,"user_password":"Abcd1234","code":"10.128.202.10","memory":"","login_port":"3306","r_guid":"0015_0000000010","user_name":"root","description":"","master_resource_instance":"0015_0000000009","storage":1000,"unit_type":66,"resource_instance_type":112,"billing_cycle":0,"state":40,"fixed_date":"","resource_instance_spec":125,"cluster_node_type":131,"cpu":"","resource_set":"0022_0000000021","resource_system":119,"key_name":"GZ3P_MGMT_MT_DB_10.128.202.10","p_guid":null,"asset_code":"","name":"db1","guid":"0015_0000000010","intranet_ip":"0017_0000000041"}]

Response：
{"statusCode":"ERR_BATCH_CHANGE","statusMessage":"Fail to update [1] records, detail error in the data block","data":[{"errorMessage":"Fail to update ci data ciTypeId [15], error [The given fileter name [15$guid] can not be found out in integration query criteria. ]"}]}
**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by jordanzhangsz** [comment]
该问题已解决，见https://github.com/WeBankPartners/we-cmdb/issues/610
