### ISSUE TITLE
查询CI数据重置过滤条件后查询请求仍然包含查询条件

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#593]
**描述您遇到的bug**  
查询CI数据重置过滤条件后查询请求仍然包含查询条件。
![image](https://user-images.githubusercontent.com/17095701/71508073-97467e00-28c1-11ea-9b1d-5bf53004580c.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by zhangsenfeng** [comment]
Fixed in #671
