### ISSUE TITLE
交易时序图 - 适应新模型

### ISSUE THREAD

**Issue by jordanzhangsz** [WeBankPartners/we-cmdb#597]
**描述您的需求**  
服务调用时序序列改为按钮，目前是下拉框不正确：
![image](https://user-images.githubusercontent.com/43606056/71570954-c3a50900-2b12-11ea-9e1c-5bcb6926dade.png)

**预期行为**  
![image](https://user-images.githubusercontent.com/43606056/71570991-049d1d80-2b13-11ea-906b-185f3f414521.png)

**Comment by zhangsenfeng** [comment]
fixed in #607
