### ISSUE TITLE
用户的数据权限未根据配置受控

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#604]
**描述您遇到的bug**  
用户的数据权限未根据配置受控。如用户yoyo无服务设计的增删改查数据权限，仍然可以在CI数据管理页面对“服务设计”CI进行数据的增删改查。
![image](https://user-images.githubusercontent.com/17095701/66728414-579df780-ee77-11e9-83d7-891a16e4d757.png)
![image](https://user-images.githubusercontent.com/17095701/66730896-fb42d400-ee86-11e9-9aa9-cf4055484bc9.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by jordanzhangsz** [comment]
这是因为没有开启安全模式运行WeCMDB所致。
