### ISSUE TITLE
初始化块存储CI的云硬盘类型枚举键配置错误

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#605]
**描述您遇到的bug**  
初始化块存储CI的云硬盘类型枚举“block_storage_type“的枚举键配置错误。

![image](https://user-images.githubusercontent.com/17095701/65664668-68273300-e06c-11e9-8158-5b5aac9c5fa5.png)

硬盘介质类型。取值范围应如下：
CLOUD_BASIC：表示普通云硬盘
CLOUD_PREMIUM：表示高性能云硬盘
CLOUD_SSD：表示SSD云硬盘。

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by jordanzhangsz** [comment]
这个属于用户使用问题，私有枚举属于用户录取的数据。如将来把这些数据作为最佳实践的体验数据，那么就需要调整初始化的体验数据。
