### ISSUE TITLE
配置CI数据过滤权限后新增CI数据时会导致自动填充的key name为空

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#616]
**描述您遇到的bug**  
配置CI数据过滤权限后新增CI数据会导致key name为空：
1. 系统设计CI配置数据权限查询权限为“业务群组B”
![image](https://user-images.githubusercontent.com/17095701/71877557-650c0a80-3164-11ea-8d92-4e9921b9d48a.png)
2. 新增CI数据选择“业务群组A”
![image](https://user-images.githubusercontent.com/17095701/71877651-b74d2b80-3164-11ea-89d3-af9970b3785a.png)
3. 新增的CI数据没有自动填充key name
![image](https://user-images.githubusercontent.com/17095701/71877740-e2d01600-3164-11ea-9d66-9d91e3f7dc89.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by zgyzgyhero** [comment]
已修复
