### ISSUE TITLE
IE11登录后页面空白

### ISSUE THREAD

**Issue by hforlove** [WeBankPartners/we-cmdb#617]
**描述您遇到的bug**  
IE11登录后页面空白

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
你好，
首先感谢您的使用。
这个问题是的确存在的，在CMDB的初期，还没有对很多浏览器进行兼容性支持和相应的测试，后续会对这类问题进行优化，会在支持了IE11浏览器后通知您，抱歉给您带来不便。

同时，欢迎对CMDB提出跟多宝贵的意见和建议，我们会持续改进。谢谢

**Comment by homiexie** [comment]
初步判断为：采用的依赖包中采用了IE11不支持的es6语法，在打包时没有编译成es5。
感谢您的使用，欢迎对CMDB提出更多宝贵的意见和建议
