### ISSUE TITLE
有个疑问在base.js中axios的拦截器中

### ISSUE THREAD

**Issue by yajunfan** [WeBankPartners/we-cmdb#623]
![1578640225(1)](https://user-images.githubusercontent.com/19145057/72133000-5b301480-33bb-11ea-8c88-5bbe9a6ff1d4.jpg)
req.interceptors.response.use(
  res => {
    if (res.status === 200) {
      if (res.data.statusCode.startsWith("ERR")) {
        const errorMes = Array.isArray(res.data.data)
          ? res.data.data.map(_ => _.errorMessage).join("<br/>")
          : res.data.statusMessage;
        Vue.prototype.$Notice.error({
          title: "Error",
          desc: errorMes,
          duration: 0
        });
      }
      if (!res.headers["username"]) {
        window.location.href = "/wecmdb/logout";
      }
      return {
        ...res.data,
        user: res.headers["username"] || " - "
      };
    } else {
      return {
        data: throwError(res)
      };
    }
  },
  res => {
    const { response } = res;
    Vue.prototype.$Notice.error({
      title: "error",
      desc:
        (response.data &&
          "status:" +
            response.data.status +
            "<br/> error:" +
            response.data.error +
            "<br/> message:" +
            response.data.message) ||
        "error"
    });
    return new Promise((resolve, reject) => {
      resolve({
        data: throwError(res)
      });
    });
  }
);
use中的两个参数的参数都是res使我不太明白，是否第二个res指的是error

**Comment by zhangsenfeng** [comment]
@yajunfan 第二个参数的确指的是error，此处参数命名有些问题，非常感谢你的指正

**Comment by homiexie** [comment]
> ![1578640225(1)](https://user-images.githubusercontent.com/19145057/72133000-5b301480-33bb-11ea-8c88-5bbe9a6ff1d4.jpg)
> req.interceptors.response.use(
> res => {
> if (res.status === 200) {
> if (res.data.statusCode.startsWith("ERR")) {
> const errorMes = Array.isArray(res.data.data)
> ? res.data.data.map(_ => _.errorMessage).join("
> ")
> : res.data.statusMessage;
> Vue.prototype.$Notice.error({
> title: "Error",
> desc: errorMes,
> duration: 0
> });
> }
> if (!res.headers["username"]) {
> window.location.href = "/wecmdb/logout";
> }
> return {
> ...res.data,
> user: res.headers["username"] || " - "
> };
> } else {
> return {
> data: throwError(res)
> };
> }
> },
> res => {
> const { response } = res;
> Vue.prototype.$Notice.error({
> title: "error",
> desc:
> (response.data &&
> "status:" +
> response.data.status +
> "
> error:" +
> response.data.error +
> "
> message:" +
> response.data.message) ||
> "error"
> });
> return new Promise((resolve, reject) => {
> resolve({
> data: throwError(res)
> });
> });
> }
> );
> use中的两个参数的参数都是res使我不太明白，是否第二个res指的是error

感谢您帮我们指出这个问题，第二个res确实是指的error。后续我们会加强代码规范，也欢迎您继续向我们提出建议或意见。

**Comment by zhangsenfeng** [comment]
@yajunfan 
感谢该问题的提出，目前该问题已在#630修改。
借此机会，我们讨论了代码规范的问题，并在代码中使用了ESLint检查语法，并重新整理了Prettier的配置。
