### ISSUE TITLE
CI属性提交失败

### ISSUE THREAD

**Issue by xuxuzhesi** [WeBankPartners/we-cmdb#639]
添加一个以前存在，但被删除的属性，提交时报错
![image](https://user-images.githubusercontent.com/27829483/72341519-6fe71200-3705-11ea-92d0-8a5ff51cb8fc.png)
原因：
删除时仅改变状态，物理表的相关字段未删除，当再次添加提交，数据库抛Duplicate column Exception

**Comment by chaneyliu** [comment]
不允许添加重名属性。
