### ISSUE TITLE
国际化问题

### ISSUE THREAD

**Issue by irvinezhao** [WeBankPartners/we-cmdb#683]
**描述您遇到的bug**  

![image](https://user-images.githubusercontent.com/17263271/74621103-8524e580-5176-11ea-9130-9c9b83a115e8.png)
![image](https://user-images.githubusercontent.com/17263271/74621105-87873f80-5176-11ea-8a33-639409179c14.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by zhangsenfeng** [comment]
Fixed in #686
