### ISSUE TITLE
应用架构设计历史数据查询无数据

### ISSUE THREAD

**Issue by xuxuzhesi** [WeBankPartners/we-cmdb#696]
描述：应用架构设计，定版之后，查询历史版本，历史版本的CI无数据

原因：定版之后，系统设计的历史数据的guid改变了，子模块关联的还是以前的guid，所以查不出数据

解决方案：查询历史数据的参数由guid改为r_guid

**Comment by zhangsenfeng** [comment]
Fixed in #699
