### ISSUE TITLE
调用时序图优化

### ISSUE THREAD

**Issue by zhangsenfeng** [WeBankPartners/we-cmdb#718]
**描述您遇到的bug**  
目前的调用时序图，使用多选下拉框来选择 **调用关系** ，但这样无法重复选择相同的调用关系，

**预期行为** 
需要将该下拉框改为单选下拉框，并允许重复选择 **调用关系** 

**截图**  
![image](https://user-images.githubusercontent.com/26812573/76510986-6d96ff00-648d-11ea-87b9-714c29c155da.png)

**Comment by irvinezhao** [comment]
fixed
