### ISSUE TITLE
CMDB模型管理页面切换图层看不到非第一层级的CI

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#721]
**描述您遇到的bug**  
CMDB模型管理页面切换图层看不到非第一层级的CI。
![image](https://user-images.githubusercontent.com/17095701/76728550-fe255600-6791-11ea-8428-2710648d9840.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by zhangsenfeng** [comment]
Fixed in #739
