### ISSUE TITLE
CI数据管理和CI数据查询页面未支持非第一层CI的管理

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#722]
**描述您遇到的bug**  
CI数据管理和CI数据查询页面当前只显示第一层CI，未支持非第一层CI的管理。
![image](https://user-images.githubusercontent.com/17095701/76728866-c79c0b00-6792-11ea-8e14-e9ec330b40f6.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by zhangsenfeng** [comment]
Fixed in #739
