### ISSUE TITLE
CMDB新增层级报错提示不明确

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#723]
**描述您遇到的bug**  
CMDB新增层级输入字符超长错误提示不明确
![image](https://user-images.githubusercontent.com/17095701/76730716-c836a080-6796-11ea-99f0-a5e5aada6c9f.png)
CMDB新增层级输入JS脚本错误提示不明确
![image](https://user-images.githubusercontent.com/17095701/76730844-0f249600-6797-11ea-8311-908598a1ac70.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by junchensz** [comment]
前端截图的错误信息过于简单，不容易定位问题，最好可以提供cmdb log的exception callstack.
