### ISSUE TITLE
新增CI属性不支持新增orchestration_multi_ref 和orchestration_ref这两个数据类型

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#725]
**描述您遇到的bug**  
新增CI属性不支持新增orchestration_multi_ref 和orchestration_ref这两个数据类型。这两个数据类型是不是特殊类型？如果前端页面不支持数据类型的不应在前端提供可选。如果需要支持这两种数据类型应补充完整的字段供新增。
![image](https://user-images.githubusercontent.com/17095701/76733647-3336a600-679c-11ea-8ae6-768dbe874127.png)
![image](https://user-images.githubusercontent.com/17095701/76733165-44cb7e00-679b-11ea-8422-5147a60a3108.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by zhangsenfeng** [comment]
@xuxuzhesi 是否考虑这两种类型不返回前端？
