### ISSUE TITLE
新增CI数据失败且错误提示不明确

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#728]
**描述您遇到的bug**  
新增CI数据失败且错误提示不明确。
![image](https://user-images.githubusercontent.com/17095701/76739593-63377680-67a7-11ea-9962-118981b23e03.png)

Request URL: https://sandbox.webank.com/wecmdb/ui/v2/ci-types/45/ci-data/batch-create
Requst Payload:[{"guid":"","p_guid":null,"r_guid":"","state":"","fixed_date":"","code":"a","description":"b","text":"abcdefghijklmn","date":"2020-03-17","textarea":"abcdefghijklmnopqrstuvwxyz","select":"","multiselect":[],"ref":"0001_0000000003","multiref":["0002_0000000020","0002_0000000017"],"number":"-1","pwd":"1111"}]
Response:
{"statusCode":"ERR_BATCH_CHANGE","statusMessage":"Fail to create [1] records, detail error in the data block","data":[{"errorMessage":"Fail to create ci data ciTypeId [45], error [null]"}]}

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by chaneyliu** [comment]
已修复
