### ISSUE TITLE
新增枚举保存报错提示错误信息不明确

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#729]
**描述您遇到的bug**  
新增枚举保存报错提示错误信息不明确。
![image](https://user-images.githubusercontent.com/17095701/76741191-1a34f180-67aa-11ea-99a5-affa356330d5.png)

Request URL: https://sandbox.webank.com/wecmdb/ui/v2/enum/category-types/0/categories/undefined/codes/create

Payload: {"callbackId":1,"code":"a","status":"","value":"a","groupCodeId":""}

Response: {"statusCode":"ERROR","statusMessage":"Failed to convert value of type 'java.lang.String' to required type 'java.lang.Integer'; nested exception is java.lang.NumberFormatException: For input string: \"undefined\""}
**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by chaneyliu** [comment]
已修复
