### ISSUE TITLE
新增CI属性关键字段缺失时报错信息不明确

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#732]
**描述您遇到的bug**  
新增CI属性关键字段缺失时报错信息不明确。
![image](https://user-images.githubusercontent.com/17095701/76832943-57aa8500-6865-11ea-87c9-9c872d7af6a6.png)

Request URL: https://sandbox.webank.com/wecmdb/ui/v2/ci-types/46/attributes/create
Method: POST

Payload:
{"isAccessControlled":false,"isAuto":false,"isDisplayed":true,"isEditable":true,"isUnique":false,"isNullable":true,"isRefreshable":false,"searchSeqNo":0,"inputType":"select","propertyType":"int","referenceId":20,"length":1,"callbackId":"10000001"}

Response:
{"statusCode":"ERR_BATCH_CHANGE","statusMessage":"Fail to create [1] records, detail error in the data block","data":[{"callbackId":"10000001","errorMessage":"Fail to create record with callbackId = [10000001], error = [Validation failed for classes [com.webank.cmdb.domain.AdmCiTypeAttr] during persist time for groups [javax.validation.groups.Default, ]\nList of constraint violations:[\n\tConstraintViolationImpl{interpolatedMessage='must not be null', propertyPath=propertyName, rootBeanClass=class com.webank.cmdb.domain.AdmCiTypeAttr, messageTemplate='{javax.validation.constraints.NotNull.message}'}\n\tConstraintViolationImpl{interpolatedMessage='must not be null', propertyPath=name, rootBeanClass=class com.webank.cmdb.domain.AdmCiTypeAttr, messageTemplate='{javax.validation.constraints.NotNull.message}'}\n]]"}]}

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by chaneyliu** [comment]
已修复
