### ISSUE TITLE
CI数据管理页面有时会打开两个相同的tab且页面无响应

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#735]
**描述您遇到的bug**  
CI数据管理页面有时会打开两个相同的CI Type或两个相同的“CMDB模型”， 页面无响应。
![image](https://user-images.githubusercontent.com/17095701/76841735-29807180-6874-11ea-9895-ce73046e6e6a.png)

![image](https://user-images.githubusercontent.com/17095701/77130809-485d4e80-6a94-11ea-92f0-68f0fcabe679.png)
![image](https://user-images.githubusercontent.com/17095701/77141292-4f498880-6ab7-11ea-8ed1-dd0e45061301.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by zhangsenfeng** [comment]
这个问题是由于快速连续点击相同的CI导致的

**Comment by zhangsenfeng** [comment]
Fixed in #771
