### ISSUE TITLE
CMDB模型不能展示跨层的关联线

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#759]
**描述您遇到的bug**  
模型图像网络区域和网络区域连接之间没有关联关系的线。
如：模型图网络区域和网络区域连接之间没有关联关系的线
![image](https://user-images.githubusercontent.com/17095701/77525041-5dd2de00-6ec3-11ea-995c-a36448cf4d3a.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by zhangsenfeng** [comment]
Fixed in #777
