### ISSUE TITLE
CMDB模型管理新增层提交后，页面刷新时图层选项为空导致模型图未展示

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#761]
**描述您遇到的bug**  
CMDB模型管理新增层提交后，页面刷新时图层选项为空导致模型图未展示。
![image](https://user-images.githubusercontent.com/17095701/77548573-b0bf8c00-6ee9-11ea-8e2c-4e69a2c297fe.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by zhangsenfeng** [comment]
Fixed in #780
