### ISSUE TITLE
CMDB模型管理配置填充规则提交的auto rule会生成很多空格连接符，而且空格在界面上又不可见不可编辑

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#766]
**描述您遇到的bug**  
CMDB模型管理配置填充规则添加删除添加属性等操作后提交的auto rule会生成很多空格。而且空格在界面上又不可见不可编辑。
![image](https://user-images.githubusercontent.com/17095701/77673930-cefaba00-6fc5-11ea-853d-be678e1f3278.png)

autoFillRule: "[{"type":"delimiter","value":"   "},{"type":"delimiter","value":" "},{"type":"delimiter","value":" "},{"type":"delimiter","value":"    "},{"type":"rule","value":"[{\"ciTypeId\":25},{\"ciTypeId\":23,\"parentRs\":{\"attrId\":403,\"isReferedFromParent\":1}},{\"ciTypeId\":23,\"parentRs\":{\"attrId\":360,\"isReferedFromParent\":1}}]"},{"type":"delimiter","value":"_"},{"type":"rule","value":"[{\"ciTypeId\":25},{\"ciTypeId\":25,\"parentRs\":{\"attrId\":407,\"isReferedFromParent\":1}}]"},{"type":"delimiter","value":"_"},{"type":"rule","value":"[{\"ciTypeId\":25},{\"ciTypeId\":23,\"parentRs\":{\"attrId\":405,\"isReferedFromParent\":1}},{\"ciTypeId\":23,\"parentRs\":{\"attrId\":360,\"isReferedFromParent\":1}}]"},{"type":"delimiter","value":"_"},{"type":"rule","value":"[{\"ciTypeId\":25},{\"ciTypeId\":25,\"parentRs\":{\"attrId\":406,\"isReferedFromParent\":1}}]"},{"type":"delimiter","value":"_"},{"type":"rule","value":"[{\"ciTypeId\":25},{\"ciTypeId\":25,\"parentRs\":{\"attrId\":409,\"isReferedFromParent\":1}}]"}]"

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by zhangsenfeng** [comment]
Fixed in #779
