### ISSUE TITLE
打开业务区域CI点击新增按钮报错

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#772]
**描述您遇到的bug**  
打开业务区域CI点击新增按钮报sql error。
![image](https://user-images.githubusercontent.com/17095701/77816749-40d71e80-7100-11ea-99aa-cd097f13e6a6.png)
[cmdb01.txt](https://github.com/WeBankPartners/we-cmdb/files/4396723/cmdb01.txt)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by zhangsenfeng** [comment]
![image](https://user-images.githubusercontent.com/26812573/77884137-17043000-7297-11ea-9cf7-87a4219f0e67.png)
![image](https://user-images.githubusercontent.com/26812573/77884249-46b33800-7297-11ea-84a5-9feecb2091d1.png)
@xuxuzhesi 这里有几个接口报错了，麻烦看一下
