### ISSUE TITLE
修改网段编码，子网掩码不会同步修改

### ISSUE THREAD

**Issue by szsyyk** [WeBankPartners/we-cmdb#823]
**描述您遇到的bug**  
机房资源规划--网段中，修改编码中的掩码段（10.128.128.0/25 -》 10.128.128.0/24），但是子网掩码字段不会同步改成24.

**截图**  
![image](https://user-images.githubusercontent.com/43024934/78882514-c2c53100-7a8a-11ea-8fd7-424ab3769a9d.png)

**Comment by irvinezhao** [comment]
编码 字段不是自动填充 需要手动改写
