### ISSUE TITLE
复制新增的数据提交时报错信息不明确，建议提交报错时不要退出批量新增的录入页面

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#839]
**描述您遇到的bug**  
复制新增的数据提交时报错信息不明确，建议提交报错时不要退出批量新增的录入页面。
![image](https://user-images.githubusercontent.com/17095701/79206314-bc133100-7e71-11ea-8eb8-be0638a26c1f.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
#821
