### ISSUE TITLE
应用部署树状逻辑图使用图标优化

### ISSUE THREAD

**Issue by irvinezhao** [WeBankPartners/we-cmdb#853]
获取接口加一个字段 返回imageFieldId

![image](https://user-images.githubusercontent.com/17263271/80068057-86590100-8571-11ea-97a5-dd14030bd2ad.png)
![image](https://user-images.githubusercontent.com/17263271/80068082-907aff80-8571-11ea-99ef-021bf423e7e0.png)

**Comment by junchensz** [comment]
/wecmdb/ui/v2/trees/all-deploy-trees/from-system?system-guid=0046_0000000003
