### ISSUE TITLE
数据权限控制无法新增Select类型的字段

### ISSUE THREAD

**Issue by junchensz** [WeBankPartners/we-cmdb#902]
**描述您遇到的bug**  
在新增数据权限项的时候，无法选择select类型的字段

**如何重现** 
1. "CMDB数据模型管理", 选择"单元设计", 在右侧选择"状态"栏位
![image](https://user-images.githubusercontent.com/8709231/80558842-4e890800-8a0e-11ea-9992-31b0997c77ca.png)

2. "权限控制"属性选择"YES"
![image](https://user-images.githubusercontent.com/8709231/80558887-724c4e00-8a0e-11ea-86a7-2ee18d43bcbd.png)

3. "CMDB权限管理", 角色->”系统管理员", 数据权限 -> "单元设计", 点击"详情"
![image](https://user-images.githubusercontent.com/8709231/80558965-b5a6bc80-8a0e-11ea-904e-bbd9a8942ec0.png)

4. 在"编辑数据权限"对话框可以看到"状态"栏位
![image](https://user-images.githubusercontent.com/8709231/80559029-eab30f00-8a0e-11ea-9383-fed1b9abea01.png)

5. 点击"新增", 在"新增"对话框没有"状态"栏位
![image](https://user-images.githubusercontent.com/8709231/80559085-1504cc80-8a0f-11ea-9877-fc68713eda18.png)

![image](https://user-images.githubusercontent.com/8709231/80559115-24841580-8a0f-11ea-865f-67d40c117bba.png)

**预期行为** 

**截图**  

**附加**

**Comment by zhangsenfeng** [comment]
数据权限管理中，详情里有哪些列是由后台提供的（/ui/v2/admin/role-citypes/9/ctrl-attributes）
