### ISSUE TITLE
新增CMDB数据权限配置报错

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#936]
**描述您遇到的bug**  
新增CMDB数据权限配置报错。
![image](https://user-images.githubusercontent.com/17095701/82399873-a30d2980-9a88-11ea-9827-fd98cda9f186.png)

![image](https://user-images.githubusercontent.com/17095701/82399544-f2068f00-9a87-11ea-8156-6cb93a1ca53d.png)

Request URL: http://111.230.161.237:19090/wecmdb/ui/v2/admin/role-citypes/626/ctrl-attributes/create

Request Payload：
[{"state":{"conditionType":"Select","conditionValueSelects":[37]},"subsys":{"conditionType":"Expression","conditionValueExprs":["subsys:[guid].app_system>app_system[{app_system_design in ['0037_0000000004','0037_0000000003','0037_0000000002','0037_0000000001']}]"]},"enquiryPermission":"Y","creationPermission":"Y","modificationPermission":"Y","executionPermission":"Y","removalPermission":"Y","callbackId":1589943006570}]

Response:
{"statusCode":"ERROR","statusMessage":"Route expression is invalid (subsys:[guid].app_system>app_system[{app_system_design in ['0037_0000000004','0037_0000000003','0037_0000000002','0037_0000000001']}]). (Can't find field (app_system_design) for ci type ('subsys'))"}

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by chaneyliu** [comment]
已修复解决。
