### ISSUE TITLE
新增CMDB数据权限后台报错空指针异常

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/we-cmdb#944]
**描述您遇到的bug**  
wecmdb_v1.4.4.9
新增CMDB数据权限后台报错空指针异常。

Request URL: http://111.230.161.237:19090/wecmdb/ui/v2/admin/role-citypes/626/ctrl-attributes/create

Payload：
[{"state":null,"subsys":null,"resource_set":{"conditionType":"Expression","conditionValueExprs":[null]},"enquiryPermission":"Y","creationPermission":"Y","modificationPermission":"Y","executionPermission":"Y","removalPermission":"Y","callbackId":1589962618797}]

Response：
{"statusCode":"ERROR"}
![image](https://user-images.githubusercontent.com/17095701/82423855-f5653f00-9ab6-11ea-8aa5-817a341b0b9b.png)

![image](https://user-images.githubusercontent.com/17095701/82423641-a28b8780-9ab6-11ea-9cdd-389b6a8ecfb2.png)
**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by chaneyliu** [comment]
已修复解决
