### ISSUE TITLE
make build出现error

### ISSUE THREAD

**Issue by phoenixgcy** [WeBankPartners/we-cmdb#984]
**描述您遇到的bug**  
we-cmdb执行make build，出现以下问题：
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] cmdb-ui ............................................ SUCCESS [06:35 min]
[INFO] cmdb-core .......................................... FAILURE [01:29 min]
[INFO] cmdb ............................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 08:29 min
[INFO] Finished at: 2020-06-17T06:17:47+00:00
[INFO] Final Memory: 47M/114M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project cmdb-core: Could not resolve dependencies for project com.webank.cmdb:cmdb-core:jar:1.4.3-SNAPSHOT: Could not find artifact com.webank.wecube.platform:platform-auth-client:jar:1.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :cmdb-core
make: *** [build] 错误 1

**如何重现** 
 

**预期行为** 
 

**截图**  

 
**附加**

**Comment by junchensz** [comment]
暂时需要先在本地maven install platform-auth-client (https://github.com/WeBankPartners/wecube-platform/tree/master/platform-auth-client), 编译成功后再编译we-cmdb.

**Comment by royl88** [comment]
最新cmdb版本>= v1.5.6已无需platform-auth-client，可以直接build
