### ISSUE TITLE
Description	Resource	Path	Location	Type The container 'Maven Dependencies' references non existing library 'E:\develop\repo\com\webank\wecube\platform\platform-auth-client\1.0-SNAPSHOT\platform-auth-client-1.0-SNAPSHOT.jar'	cmdb-core		Build path	Build Path Problem

### ISSUE THREAD

**Issue by wind0503** [WeBankPartners/we-cmdb#994]
Description	Resource	Path	Location	Type
The container 'Maven Dependencies' references non existing library 'E:\develop\repo\com\webank\wecube\platform\platform-auth-client\1.0-SNAPSHOT\platform-auth-client-1.0-SNAPSHOT.jar'	cmdb-core		Build path	Build Path Problem

**Comment by royl88** [comment]
最新cmdb版本>= v1.5.6已无需platform-auth-client，可以直接build
