### ISSUE TITLE
提供一个功能，可以检测模型表达式的有效性

### ISSUE THREAD

**Issue by BenJaMiniature** [WeBankPartners/we-cmdb#997]
**描述您的需求**  
提供一个功能，可以检测模型表达式的有效性，特别是在模型升级后；
差异化变量中配置的模型表达式可能失效，从而导致无法在应用实例中绑定部署包。
如果有功能可以检测模型表达式的正确性，则可以在升级模型后检测所有表达式，提前暴露问题，避免后续出现问题难以定位。

**预期行为**  

**描述您考虑过的替代方案**  

**附加**
![image](https://user-images.githubusercontent.com/52971115/86194741-dc55b080-bb81-11ea-818d-8f60245917e6.png)
![image](https://user-images.githubusercontent.com/52971115/86194755-e4adeb80-bb81-11ea-94a7-4113afdfc106.png)

**Comment by zgyzgyhero** [comment]
当前可以支持到表达式配置中检测依赖关系避免死循环等效验
